// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinylRecordSale.Infra.Data.Contexts;

namespace VinylRecordSale.Service.Api.Migrations
{
    [DbContext(typeof(ContextEf))]
    [Migration("20191205131949_Migration-Initial")]
    partial class MigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VinylRecordSale")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Email = "karlafranco59@hotmail.com",
                            FullName = "Karla Franco"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "victorcarvalho.Barros@live.com",
                            FullName = "Víctor Carvalho"
                        },
                        new
                        {
                            ClientId = 3,
                            Email = "felicianobatista.Costa3@bol.com.br",
                            FullName = "Feliciano Batista"
                        },
                        new
                        {
                            ClientId = 4,
                            Email = "juliasantos_Albuquerque29@yahoo.com",
                            FullName = "Júlia Santos"
                        },
                        new
                        {
                            ClientId = 5,
                            Email = "ceciliabarros85@hotmail.com",
                            FullName = "Cecília Barros"
                        },
                        new
                        {
                            ClientId = 6,
                            Email = "isabelaalbuquerque_Saraiva@live.com",
                            FullName = "Isabela Albuquerque"
                        },
                        new
                        {
                            ClientId = 7,
                            Email = "alessandraoliveira.Oliveira43@hotmail.com",
                            FullName = "Alessandra Oliveira"
                        },
                        new
                        {
                            ClientId = 8,
                            Email = "dalilanogueira.Oliveira85@yahoo.com",
                            FullName = "Dalila Nogueira"
                        },
                        new
                        {
                            ClientId = 9,
                            Email = "raulalbuquerque62@gmail.com",
                            FullName = "Raul Albuquerque"
                        },
                        new
                        {
                            ClientId = 10,
                            Email = "salvadorsaraiva27@hotmail.com",
                            FullName = "Salvador Saraiva"
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ConfigCashback", b =>
                {
                    b.Property<int>("MusicGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("PercentageFriday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageMonday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageSaturday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageSunday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageThursday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageTuesday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageWednesday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("MusicGenreId");

                    b.ToTable("ConfigCashbacks");

                    b.HasData(
                        new
                        {
                            MusicGenreId = 1,
                            PercentageFriday = 15m,
                            PercentageMonday = 7m,
                            PercentageSaturday = 20m,
                            PercentageSunday = 25m,
                            PercentageThursday = 10m,
                            PercentageTuesday = 6m,
                            PercentageWednesday = 2m
                        },
                        new
                        {
                            MusicGenreId = 2,
                            PercentageFriday = 25m,
                            PercentageMonday = 5m,
                            PercentageSaturday = 30m,
                            PercentageSunday = 30m,
                            PercentageThursday = 20m,
                            PercentageTuesday = 10m,
                            PercentageWednesday = 15m
                        },
                        new
                        {
                            MusicGenreId = 3,
                            PercentageFriday = 18m,
                            PercentageMonday = 3m,
                            PercentageSaturday = 25m,
                            PercentageSunday = 35m,
                            PercentageThursday = 13m,
                            PercentageTuesday = 5m,
                            PercentageWednesday = 8m
                        },
                        new
                        {
                            MusicGenreId = 4,
                            PercentageFriday = 20m,
                            PercentageMonday = 10m,
                            PercentageSaturday = 40m,
                            PercentageSunday = 40m,
                            PercentageThursday = 15m,
                            PercentageTuesday = 15m,
                            PercentageWednesday = 15m
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ItemSale", b =>
                {
                    b.Property<int>("ItemSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cashback")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VinylDiscId")
                        .HasColumnType("int");

                    b.HasKey("ItemSaleId");

                    b.HasIndex("SaleId");

                    b.HasIndex("VinylDiscId");

                    b.ToTable("ItemSales");
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.MusicGenre", b =>
                {
                    b.Property<int>("MusicGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MusicGenreId");

                    b.ToTable("MusicGenres");

                    b.HasData(
                        new
                        {
                            MusicGenreId = 1,
                            Description = "Pop"
                        },
                        new
                        {
                            MusicGenreId = 2,
                            Description = "Mpb"
                        },
                        new
                        {
                            MusicGenreId = 3,
                            Description = "Classic"
                        },
                        new
                        {
                            MusicGenreId = 4,
                            Description = "Rock"
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CashbackTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("ClientId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.VinylDisc", b =>
                {
                    b.Property<int>("VinylDiscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MusicGenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("VinylDiscId");

                    b.HasIndex("MusicGenreId");

                    b.ToTable("VinylDiscs");

                    b.HasData(
                        new
                        {
                            VinylDiscId = 1,
                            MusicGenreId = 1,
                            Name = "Playboi Carti",
                            Value = 94.05m
                        },
                        new
                        {
                            VinylDiscId = 2,
                            MusicGenreId = 1,
                            Name = "This Is A Challenge",
                            Value = 99.30m
                        },
                        new
                        {
                            VinylDiscId = 3,
                            MusicGenreId = 1,
                            Name = "After Laughter",
                            Value = 87.07m
                        },
                        new
                        {
                            VinylDiscId = 4,
                            MusicGenreId = 1,
                            Name = "The 1975",
                            Value = 97.77m
                        },
                        new
                        {
                            VinylDiscId = 5,
                            MusicGenreId = 1,
                            Name = "Luv Is Rage 2",
                            Value = 47.02m
                        },
                        new
                        {
                            VinylDiscId = 6,
                            MusicGenreId = 1,
                            Name = "Views",
                            Value = 27.82m
                        },
                        new
                        {
                            VinylDiscId = 7,
                            MusicGenreId = 1,
                            Name = "There for You",
                            Value = 45.83m
                        },
                        new
                        {
                            VinylDiscId = 8,
                            MusicGenreId = 1,
                            Name = "Red Pill Blues (Deluxe)",
                            Value = 47.67m
                        },
                        new
                        {
                            VinylDiscId = 9,
                            MusicGenreId = 1,
                            Name = "Boys",
                            Value = 45.07m
                        },
                        new
                        {
                            VinylDiscId = 10,
                            MusicGenreId = 1,
                            Name = "Melodrama",
                            Value = 77.23m
                        },
                        new
                        {
                            VinylDiscId = 11,
                            MusicGenreId = 1,
                            Name = "Still Got Time",
                            Value = 65.83m
                        },
                        new
                        {
                            VinylDiscId = 12,
                            MusicGenreId = 1,
                            Name = "A Town Called Paradise",
                            Value = 87.29m
                        },
                        new
                        {
                            VinylDiscId = 13,
                            MusicGenreId = 1,
                            Name = "Talking Dreams (Deluxe Version)",
                            Value = 85.69m
                        },
                        new
                        {
                            VinylDiscId = 14,
                            MusicGenreId = 1,
                            Name = "Artist",
                            Value = 29.91m
                        },
                        new
                        {
                            VinylDiscId = 15,
                            MusicGenreId = 1,
                            Name = "War & Leisure",
                            Value = 55.12m
                        },
                        new
                        {
                            VinylDiscId = 16,
                            MusicGenreId = 1,
                            Name = "Just Hold On",
                            Value = 33.26m
                        },
                        new
                        {
                            VinylDiscId = 17,
                            MusicGenreId = 1,
                            Name = "Your Song",
                            Value = 31.22m
                        },
                        new
                        {
                            VinylDiscId = 18,
                            MusicGenreId = 1,
                            Name = "Black Panther The Album Music From And Inspired By",
                            Value = 64.62m
                        },
                        new
                        {
                            VinylDiscId = 19,
                            MusicGenreId = 1,
                            Name = "From A Distance",
                            Value = 51.11m
                        },
                        new
                        {
                            VinylDiscId = 20,
                            MusicGenreId = 1,
                            Name = "Midnight Memories (Deluxe)",
                            Value = 51.72m
                        },
                        new
                        {
                            VinylDiscId = 21,
                            MusicGenreId = 1,
                            Name = "beerbongs & bentleys",
                            Value = 74.79m
                        },
                        new
                        {
                            VinylDiscId = 22,
                            MusicGenreId = 1,
                            Name = "The Click",
                            Value = 26.54m
                        },
                        new
                        {
                            VinylDiscId = 23,
                            MusicGenreId = 1,
                            Name = "BEYONCÉ [Platinum Edition]",
                            Value = 33.53m
                        },
                        new
                        {
                            VinylDiscId = 24,
                            MusicGenreId = 1,
                            Name = "My Dear Melancholy,",
                            Value = 54.59m
                        },
                        new
                        {
                            VinylDiscId = 25,
                            MusicGenreId = 1,
                            Name = "Pray for the Wicked",
                            Value = 95.38m
                        },
                        new
                        {
                            VinylDiscId = 26,
                            MusicGenreId = 1,
                            Name = "Tremaine The Album",
                            Value = 48.18m
                        },
                        new
                        {
                            VinylDiscId = 27,
                            MusicGenreId = 1,
                            Name = "The Marshall Mathers LP2",
                            Value = 23.49m
                        },
                        new
                        {
                            VinylDiscId = 28,
                            MusicGenreId = 1,
                            Name = "OMG",
                            Value = 60.25m
                        },
                        new
                        {
                            VinylDiscId = 29,
                            MusicGenreId = 1,
                            Name = "Heathens",
                            Value = 61.68m
                        },
                        new
                        {
                            VinylDiscId = 30,
                            MusicGenreId = 1,
                            Name = "Let Me Hold You (Turn Me On)",
                            Value = 71.90m
                        },
                        new
                        {
                            VinylDiscId = 31,
                            MusicGenreId = 1,
                            Name = "Culture II",
                            Value = 27.93m
                        },
                        new
                        {
                            VinylDiscId = 32,
                            MusicGenreId = 1,
                            Name = "Views",
                            Value = 88.47m
                        },
                        new
                        {
                            VinylDiscId = 33,
                            MusicGenreId = 1,
                            Name = "Skin",
                            Value = 36.02m
                        },
                        new
                        {
                            VinylDiscId = 34,
                            MusicGenreId = 1,
                            Name = "A Head Full of Dreams",
                            Value = 68.58m
                        },
                        new
                        {
                            VinylDiscId = 35,
                            MusicGenreId = 1,
                            Name = "I Decided.",
                            Value = 30.07m
                        },
                        new
                        {
                            VinylDiscId = 36,
                            MusicGenreId = 1,
                            Name = "#willpower",
                            Value = 95.50m
                        },
                        new
                        {
                            VinylDiscId = 37,
                            MusicGenreId = 1,
                            Name = "Life Changes",
                            Value = 35.12m
                        },
                        new
                        {
                            VinylDiscId = 38,
                            MusicGenreId = 1,
                            Name = "The Human Condition",
                            Value = 15.53m
                        },
                        new
                        {
                            VinylDiscId = 39,
                            MusicGenreId = 1,
                            Name = "Happier",
                            Value = 19.78m
                        },
                        new
                        {
                            VinylDiscId = 40,
                            MusicGenreId = 1,
                            Name = "The Pinkprint (Deluxe Edition)",
                            Value = 95.24m
                        },
                        new
                        {
                            VinylDiscId = 41,
                            MusicGenreId = 1,
                            Name = "SUBEME LA RADIO",
                            Value = 49.26m
                        },
                        new
                        {
                            VinylDiscId = 42,
                            MusicGenreId = 1,
                            Name = "Starboy",
                            Value = 63.58m
                        },
                        new
                        {
                            VinylDiscId = 43,
                            MusicGenreId = 1,
                            Name = "Non-Fiction (Deluxe)",
                            Value = 30.37m
                        },
                        new
                        {
                            VinylDiscId = 44,
                            MusicGenreId = 1,
                            Name = "Lady Wood",
                            Value = 58.08m
                        },
                        new
                        {
                            VinylDiscId = 45,
                            MusicGenreId = 1,
                            Name = "Globalization",
                            Value = 18.29m
                        },
                        new
                        {
                            VinylDiscId = 46,
                            MusicGenreId = 1,
                            Name = "All My Friends (feat. Tinashe & Chance the Rapper)",
                            Value = 12.61m
                        },
                        new
                        {
                            VinylDiscId = 47,
                            MusicGenreId = 1,
                            Name = "Grateful",
                            Value = 94.77m
                        },
                        new
                        {
                            VinylDiscId = 48,
                            MusicGenreId = 1,
                            Name = "Rainbow",
                            Value = 64.38m
                        },
                        new
                        {
                            VinylDiscId = 49,
                            MusicGenreId = 1,
                            Name = "I LOVE MAKONNEN",
                            Value = 84.17m
                        },
                        new
                        {
                            VinylDiscId = 50,
                            MusicGenreId = 1,
                            Name = "2014 Forest Hills Drive",
                            Value = 53.19m
                        },
                        new
                        {
                            VinylDiscId = 51,
                            MusicGenreId = 2,
                            Name = "I Love MPB - O Nosso Amor A Gente Inventa",
                            Value = 19.32m
                        },
                        new
                        {
                            VinylDiscId = 52,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 56.55m
                        },
                        new
                        {
                            VinylDiscId = 53,
                            MusicGenreId = 2,
                            Name = "O Micróbio do Samba",
                            Value = 33.60m
                        },
                        new
                        {
                            VinylDiscId = 54,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 65.22m
                        },
                        new
                        {
                            VinylDiscId = 55,
                            MusicGenreId = 2,
                            Name = "Redescobrir (Live At Credicard Hall, São Paulo / 2012)",
                            Value = 62.50m
                        },
                        new
                        {
                            VinylDiscId = 56,
                            MusicGenreId = 2,
                            Name = "Sinais dos Tempos",
                            Value = 78.41m
                        },
                        new
                        {
                            VinylDiscId = 57,
                            MusicGenreId = 2,
                            Name = "I Love MPB - O Nosso Amor A Gente Inventa",
                            Value = 76.66m
                        },
                        new
                        {
                            VinylDiscId = 58,
                            MusicGenreId = 2,
                            Name = "Acabou Chorare",
                            Value = 43.38m
                        },
                        new
                        {
                            VinylDiscId = 59,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 13.29m
                        },
                        new
                        {
                            VinylDiscId = 60,
                            MusicGenreId = 2,
                            Name = "Geraldo Azevedo",
                            Value = 98.73m
                        },
                        new
                        {
                            VinylDiscId = 61,
                            MusicGenreId = 2,
                            Name = "Vanessa da Mata canta Tom Jobim (Deluxe Edition)",
                            Value = 15.23m
                        },
                        new
                        {
                            VinylDiscId = 62,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 85.47m
                        },
                        new
                        {
                            VinylDiscId = 63,
                            MusicGenreId = 2,
                            Name = "Roupa Nova",
                            Value = 85.89m
                        },
                        new
                        {
                            VinylDiscId = 64,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 73.07m
                        },
                        new
                        {
                            VinylDiscId = 65,
                            MusicGenreId = 2,
                            Name = "Toni Ferreira",
                            Value = 60.20m
                        },
                        new
                        {
                            VinylDiscId = 66,
                            MusicGenreId = 2,
                            Name = "ôÔÔôôÔôÔ",
                            Value = 77.26m
                        },
                        new
                        {
                            VinylDiscId = 67,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 62.17m
                        },
                        new
                        {
                            VinylDiscId = 68,
                            MusicGenreId = 2,
                            Name = "A revolta dos ritmos",
                            Value = 28.01m
                        },
                        new
                        {
                            VinylDiscId = 69,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 99.74m
                        },
                        new
                        {
                            VinylDiscId = 70,
                            MusicGenreId = 2,
                            Name = "Brasis",
                            Value = 59.52m
                        },
                        new
                        {
                            VinylDiscId = 71,
                            MusicGenreId = 2,
                            Name = "Nove",
                            Value = 98.04m
                        },
                        new
                        {
                            VinylDiscId = 72,
                            MusicGenreId = 2,
                            Name = "Sinais dos Tempos",
                            Value = 26.59m
                        },
                        new
                        {
                            VinylDiscId = 73,
                            MusicGenreId = 2,
                            Name = "Meu Coração Não Quer Viver Batendo Devagar",
                            Value = 55.74m
                        },
                        new
                        {
                            VinylDiscId = 74,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 55.77m
                        },
                        new
                        {
                            VinylDiscId = 75,
                            MusicGenreId = 2,
                            Name = "O Micróbio do Samba",
                            Value = 13.37m
                        },
                        new
                        {
                            VinylDiscId = 76,
                            MusicGenreId = 2,
                            Name = "Acabou Chorare",
                            Value = 22.11m
                        },
                        new
                        {
                            VinylDiscId = 77,
                            MusicGenreId = 2,
                            Name = "A revolta dos ritmos",
                            Value = 96.07m
                        },
                        new
                        {
                            VinylDiscId = 78,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 75.36m
                        },
                        new
                        {
                            VinylDiscId = 79,
                            MusicGenreId = 2,
                            Name = "Estampado",
                            Value = 47.21m
                        },
                        new
                        {
                            VinylDiscId = 80,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 93.67m
                        },
                        new
                        {
                            VinylDiscId = 81,
                            MusicGenreId = 2,
                            Name = "Roupa Nova",
                            Value = 53.31m
                        },
                        new
                        {
                            VinylDiscId = 82,
                            MusicGenreId = 2,
                            Name = "Meu Coração Não Quer Viver Batendo Devagar",
                            Value = 59.01m
                        },
                        new
                        {
                            VinylDiscId = 83,
                            MusicGenreId = 2,
                            Name = "Acabou Chorare",
                            Value = 75.98m
                        },
                        new
                        {
                            VinylDiscId = 84,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 19.39m
                        },
                        new
                        {
                            VinylDiscId = 85,
                            MusicGenreId = 2,
                            Name = "Recanto",
                            Value = 63.47m
                        },
                        new
                        {
                            VinylDiscId = 86,
                            MusicGenreId = 2,
                            Name = "Em Pleno Verão",
                            Value = 71.28m
                        },
                        new
                        {
                            VinylDiscId = 87,
                            MusicGenreId = 2,
                            Name = "De Lá Até Aqui",
                            Value = 65.77m
                        },
                        new
                        {
                            VinylDiscId = 88,
                            MusicGenreId = 2,
                            Name = "Acabou Chorare",
                            Value = 70.70m
                        },
                        new
                        {
                            VinylDiscId = 89,
                            MusicGenreId = 2,
                            Name = "Brasis",
                            Value = 16.99m
                        },
                        new
                        {
                            VinylDiscId = 90,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 51.56m
                        },
                        new
                        {
                            VinylDiscId = 91,
                            MusicGenreId = 2,
                            Name = "Rua dos Amores",
                            Value = 29.74m
                        },
                        new
                        {
                            VinylDiscId = 92,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 91.64m
                        },
                        new
                        {
                            VinylDiscId = 93,
                            MusicGenreId = 2,
                            Name = "Recanto",
                            Value = 13.14m
                        },
                        new
                        {
                            VinylDiscId = 94,
                            MusicGenreId = 2,
                            Name = "Geraldo Azevedo",
                            Value = 20.95m
                        },
                        new
                        {
                            VinylDiscId = 95,
                            MusicGenreId = 2,
                            Name = "A revolta dos ritmos",
                            Value = 90.91m
                        },
                        new
                        {
                            VinylDiscId = 96,
                            MusicGenreId = 2,
                            Name = "Roupa Nova",
                            Value = 63.68m
                        },
                        new
                        {
                            VinylDiscId = 97,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 77.58m
                        },
                        new
                        {
                            VinylDiscId = 98,
                            MusicGenreId = 2,
                            Name = "O Micróbio do Samba",
                            Value = 57.20m
                        },
                        new
                        {
                            VinylDiscId = 99,
                            MusicGenreId = 2,
                            Name = "Musica do Brasil Antonio Carlos Jobim \"Romántico\"",
                            Value = 97.77m
                        },
                        new
                        {
                            VinylDiscId = 100,
                            MusicGenreId = 2,
                            Name = "A revolta dos ritmos",
                            Value = 40.93m
                        },
                        new
                        {
                            VinylDiscId = 101,
                            MusicGenreId = 3,
                            Name = "Haydn (The Best Of)",
                            Value = 50.34m
                        },
                        new
                        {
                            VinylDiscId = 102,
                            MusicGenreId = 3,
                            Name = "Horowitz Plays Liszt",
                            Value = 77.66m
                        },
                        new
                        {
                            VinylDiscId = 103,
                            MusicGenreId = 3,
                            Name = "Scriabin: Vers la Flamme",
                            Value = 64.54m
                        },
                        new
                        {
                            VinylDiscId = 104,
                            MusicGenreId = 3,
                            Name = "Copland Conducts Copland - Expanded Edition (Fanfare for the Common Man, Appalachian Spring, Old American Songs (Complete), Rodeo: Four Dance Episodes)",
                            Value = 35.55m
                        },
                        new
                        {
                            VinylDiscId = 105,
                            MusicGenreId = 3,
                            Name = "Fauré: Violin Sonata in E minor / Franck: Violin Sonata in A etc.",
                            Value = 55.05m
                        },
                        new
                        {
                            VinylDiscId = 106,
                            MusicGenreId = 3,
                            Name = "Wagner: Opera Orchestral Music",
                            Value = 92.63m
                        },
                        new
                        {
                            VinylDiscId = 107,
                            MusicGenreId = 3,
                            Name = "Bach: Brandenburgische Konzerte",
                            Value = 11.70m
                        },
                        new
                        {
                            VinylDiscId = 108,
                            MusicGenreId = 3,
                            Name = "The Age Of Puccini",
                            Value = 77.73m
                        },
                        new
                        {
                            VinylDiscId = 109,
                            MusicGenreId = 3,
                            Name = "Legends Of The Fall Original Motion Picture Soundtrack",
                            Value = 62.75m
                        },
                        new
                        {
                            VinylDiscId = 110,
                            MusicGenreId = 3,
                            Name = "Sibelius Finlandia (Best Of)",
                            Value = 51.28m
                        },
                        new
                        {
                            VinylDiscId = 111,
                            MusicGenreId = 3,
                            Name = "Bartók, Khachaturian, Milhaud, Stravinsky: Clarinet Trios",
                            Value = 82.24m
                        },
                        new
                        {
                            VinylDiscId = 112,
                            MusicGenreId = 3,
                            Name = "Szymanowski: Complete Piano Works",
                            Value = 12.21m
                        },
                        new
                        {
                            VinylDiscId = 113,
                            MusicGenreId = 3,
                            Name = "The Art of Bach",
                            Value = 96.07m
                        },
                        new
                        {
                            VinylDiscId = 114,
                            MusicGenreId = 3,
                            Name = "Adams, J.: Nixon in China",
                            Value = 19.52m
                        },
                        new
                        {
                            VinylDiscId = 115,
                            MusicGenreId = 3,
                            Name = "Gershwin Plays Gershwin: The Piano Rolls",
                            Value = 56.32m
                        },
                        new
                        {
                            VinylDiscId = 116,
                            MusicGenreId = 3,
                            Name = "Waghalter: Violin Concerto - Violin Sonata",
                            Value = 56.12m
                        },
                        new
                        {
                            VinylDiscId = 117,
                            MusicGenreId = 3,
                            Name = "Faure (The Best Of)",
                            Value = 20.39m
                        },
                        new
                        {
                            VinylDiscId = 118,
                            MusicGenreId = 3,
                            Name = "Bruckner: Symphony No. 8",
                            Value = 77.41m
                        },
                        new
                        {
                            VinylDiscId = 119,
                            MusicGenreId = 3,
                            Name = "Rebirth of a Nation",
                            Value = 20.49m
                        },
                        new
                        {
                            VinylDiscId = 120,
                            MusicGenreId = 3,
                            Name = "Pan's Labyrinth",
                            Value = 88.82m
                        },
                        new
                        {
                            VinylDiscId = 121,
                            MusicGenreId = 3,
                            Name = "Hope Street Tunnel Blues: Music for Piano By Philip Glass and Alvin Curran",
                            Value = 22.39m
                        },
                        new
                        {
                            VinylDiscId = 122,
                            MusicGenreId = 3,
                            Name = "Cinema Classics, Vol. 10",
                            Value = 91.37m
                        },
                        new
                        {
                            VinylDiscId = 123,
                            MusicGenreId = 3,
                            Name = "Rimsky-Korsakov: Scheherazade, Op. 35; Capriccio espagnol, Op. 34",
                            Value = 21.92m
                        },
                        new
                        {
                            VinylDiscId = 124,
                            MusicGenreId = 3,
                            Name = "Tchaikovsky: Serenade for Strings - Grieg: Holberg Suite - Mozart: Eine kleine Nachtmusik",
                            Value = 59.08m
                        },
                        new
                        {
                            VinylDiscId = 125,
                            MusicGenreId = 3,
                            Name = "Pärt: Piano Music",
                            Value = 40.68m
                        },
                        new
                        {
                            VinylDiscId = 126,
                            MusicGenreId = 3,
                            Name = "The Leftovers: Season 1 (Music from the HBO Series)",
                            Value = 17.30m
                        },
                        new
                        {
                            VinylDiscId = 127,
                            MusicGenreId = 3,
                            Name = "Martinů: Cello Sonatas Nos. 1-3",
                            Value = 24.35m
                        },
                        new
                        {
                            VinylDiscId = 128,
                            MusicGenreId = 3,
                            Name = "The Lighthouse Project",
                            Value = 45.69m
                        },
                        new
                        {
                            VinylDiscId = 129,
                            MusicGenreId = 3,
                            Name = "The Very Best of Jessye Norman",
                            Value = 64.76m
                        },
                        new
                        {
                            VinylDiscId = 130,
                            MusicGenreId = 3,
                            Name = "Ives: Symphony No. 3 / Washington's Birthday",
                            Value = 49.58m
                        },
                        new
                        {
                            VinylDiscId = 131,
                            MusicGenreId = 3,
                            Name = "Music for Egon Schiele",
                            Value = 44.43m
                        },
                        new
                        {
                            VinylDiscId = 132,
                            MusicGenreId = 3,
                            Name = "Liszt: Scherzo and March / 3 Liebestraume / Berceuse",
                            Value = 49.77m
                        },
                        new
                        {
                            VinylDiscId = 133,
                            MusicGenreId = 3,
                            Name = "Scriabin: Piano Concerto / Prometheus",
                            Value = 77.48m
                        },
                        new
                        {
                            VinylDiscId = 134,
                            MusicGenreId = 3,
                            Name = "Handel: Messiah",
                            Value = 17.18m
                        },
                        new
                        {
                            VinylDiscId = 135,
                            MusicGenreId = 3,
                            Name = "Bartók: Concerto for Orchestra - Music for Strings, Percussion & Celesta",
                            Value = 54.22m
                        },
                        new
                        {
                            VinylDiscId = 136,
                            MusicGenreId = 3,
                            Name = "Chopin: Complete Nocturnes",
                            Value = 75.55m
                        },
                        new
                        {
                            VinylDiscId = 137,
                            MusicGenreId = 3,
                            Name = "Albinoni: Oboe Concertos, Vol. 2",
                            Value = 94.38m
                        },
                        new
                        {
                            VinylDiscId = 138,
                            MusicGenreId = 3,
                            Name = "Schumann, C.: Songs (Complete)",
                            Value = 51.33m
                        },
                        new
                        {
                            VinylDiscId = 139,
                            MusicGenreId = 3,
                            Name = "Schonberg : Verklärte Nacht, 5 Orchestral Pieces & Piano Works",
                            Value = 64.24m
                        },
                        new
                        {
                            VinylDiscId = 140,
                            MusicGenreId = 3,
                            Name = "Copland Conducts Copland - Expanded Edition (Fanfare for the Common Man, Appalachian Spring, Old American Songs (Complete), Rodeo: Four Dance Episodes)",
                            Value = 70.74m
                        },
                        new
                        {
                            VinylDiscId = 141,
                            MusicGenreId = 3,
                            Name = "The Fountain OST",
                            Value = 70.48m
                        },
                        new
                        {
                            VinylDiscId = 142,
                            MusicGenreId = 3,
                            Name = "Tintomara",
                            Value = 87.94m
                        },
                        new
                        {
                            VinylDiscId = 143,
                            MusicGenreId = 3,
                            Name = "Dvořák: Serenade for Strings, Czech Suite",
                            Value = 18.85m
                        },
                        new
                        {
                            VinylDiscId = 144,
                            MusicGenreId = 3,
                            Name = "Handel: Messiah",
                            Value = 65.60m
                        },
                        new
                        {
                            VinylDiscId = 145,
                            MusicGenreId = 3,
                            Name = "Legends Of The Fall Original Motion Picture Soundtrack",
                            Value = 69.22m
                        },
                        new
                        {
                            VinylDiscId = 146,
                            MusicGenreId = 3,
                            Name = "Smetana: Ma Vlast (My Country)",
                            Value = 28.43m
                        },
                        new
                        {
                            VinylDiscId = 147,
                            MusicGenreId = 3,
                            Name = "Xenakis, I.: Orchestral Works, Vol. 5 - Metastaseis / Pithoprakta / St/48 / Achorripsis / Syrmos / Hiketides Suite",
                            Value = 95.47m
                        },
                        new
                        {
                            VinylDiscId = 148,
                            MusicGenreId = 3,
                            Name = "Beethoven: Symphony No. 3 \"Eroica\" & Leonore Overture",
                            Value = 93.52m
                        },
                        new
                        {
                            VinylDiscId = 149,
                            MusicGenreId = 3,
                            Name = "Harry Potter and The Sorcerer's Stone Original Motion Picture Soundtrack",
                            Value = 64.53m
                        },
                        new
                        {
                            VinylDiscId = 150,
                            MusicGenreId = 3,
                            Name = "Faure: Requiem, Op. 48 / Pavane, Op. 50",
                            Value = 45.70m
                        },
                        new
                        {
                            VinylDiscId = 151,
                            MusicGenreId = 4,
                            Name = "The Atlas Underground",
                            Value = 54.19m
                        },
                        new
                        {
                            VinylDiscId = 152,
                            MusicGenreId = 4,
                            Name = "The Canyon",
                            Value = 11.08m
                        },
                        new
                        {
                            VinylDiscId = 153,
                            MusicGenreId = 4,
                            Name = "Use Your Illusion II",
                            Value = 47.61m
                        },
                        new
                        {
                            VinylDiscId = 154,
                            MusicGenreId = 4,
                            Name = "Morning View",
                            Value = 19.85m
                        },
                        new
                        {
                            VinylDiscId = 155,
                            MusicGenreId = 4,
                            Name = "Graveyard Shift",
                            Value = 29.44m
                        },
                        new
                        {
                            VinylDiscId = 156,
                            MusicGenreId = 4,
                            Name = "Can't Knock The Hustle",
                            Value = 58.88m
                        },
                        new
                        {
                            VinylDiscId = 157,
                            MusicGenreId = 4,
                            Name = "Vivid (Expanded Edition)",
                            Value = 66.65m
                        },
                        new
                        {
                            VinylDiscId = 158,
                            MusicGenreId = 4,
                            Name = "Aqualung (Special Edition)",
                            Value = 16.36m
                        },
                        new
                        {
                            VinylDiscId = 159,
                            MusicGenreId = 4,
                            Name = "Stone Temple Pilots (2018)",
                            Value = 94.77m
                        },
                        new
                        {
                            VinylDiscId = 160,
                            MusicGenreId = 4,
                            Name = "Straight Shooter",
                            Value = 48.65m
                        },
                        new
                        {
                            VinylDiscId = 161,
                            MusicGenreId = 4,
                            Name = "Document (R.E.M. No. 5)",
                            Value = 79.18m
                        },
                        new
                        {
                            VinylDiscId = 162,
                            MusicGenreId = 4,
                            Name = "The Boy Who Died Wolf",
                            Value = 65.91m
                        },
                        new
                        {
                            VinylDiscId = 163,
                            MusicGenreId = 4,
                            Name = "Escape",
                            Value = 23.87m
                        },
                        new
                        {
                            VinylDiscId = 164,
                            MusicGenreId = 4,
                            Name = "American IV: The Man Comes Around",
                            Value = 24.07m
                        },
                        new
                        {
                            VinylDiscId = 165,
                            MusicGenreId = 4,
                            Name = "Is This It",
                            Value = 17.76m
                        },
                        new
                        {
                            VinylDiscId = 166,
                            MusicGenreId = 4,
                            Name = "Some Girls",
                            Value = 43.37m
                        },
                        new
                        {
                            VinylDiscId = 167,
                            MusicGenreId = 4,
                            Name = "Who Are You",
                            Value = 34.62m
                        },
                        new
                        {
                            VinylDiscId = 168,
                            MusicGenreId = 4,
                            Name = "Spotify Singles",
                            Value = 89.79m
                        },
                        new
                        {
                            VinylDiscId = 169,
                            MusicGenreId = 4,
                            Name = "The Wrong Side Of Heaven And The Righteous Side Of Hell, Volume 1",
                            Value = 65.20m
                        },
                        new
                        {
                            VinylDiscId = 170,
                            MusicGenreId = 4,
                            Name = "Toxicity",
                            Value = 80.67m
                        },
                        new
                        {
                            VinylDiscId = 171,
                            MusicGenreId = 4,
                            Name = "...Like Clockwork",
                            Value = 61.64m
                        },
                        new
                        {
                            VinylDiscId = 172,
                            MusicGenreId = 4,
                            Name = "Good Thing",
                            Value = 68.96m
                        },
                        new
                        {
                            VinylDiscId = 173,
                            MusicGenreId = 4,
                            Name = "Rumours",
                            Value = 24.07m
                        },
                        new
                        {
                            VinylDiscId = 174,
                            MusicGenreId = 4,
                            Name = "This Is War",
                            Value = 49.65m
                        },
                        new
                        {
                            VinylDiscId = 175,
                            MusicGenreId = 4,
                            Name = "Paranoid (2009 Remastered Version)",
                            Value = 29.25m
                        },
                        new
                        {
                            VinylDiscId = 176,
                            MusicGenreId = 4,
                            Name = "Ring Of Fire: The Best Of Johnny Cash",
                            Value = 34.35m
                        },
                        new
                        {
                            VinylDiscId = 177,
                            MusicGenreId = 4,
                            Name = "Ember",
                            Value = 83.42m
                        },
                        new
                        {
                            VinylDiscId = 178,
                            MusicGenreId = 4,
                            Name = "Echoes, Silence, Patience & Grace",
                            Value = 56.21m
                        },
                        new
                        {
                            VinylDiscId = 179,
                            MusicGenreId = 4,
                            Name = "The Wall (Remastered)",
                            Value = 89.75m
                        },
                        new
                        {
                            VinylDiscId = 180,
                            MusicGenreId = 4,
                            Name = "Human Clay",
                            Value = 23.15m
                        },
                        new
                        {
                            VinylDiscId = 181,
                            MusicGenreId = 4,
                            Name = "Full Moon Fever",
                            Value = 21.72m
                        },
                        new
                        {
                            VinylDiscId = 182,
                            MusicGenreId = 4,
                            Name = "Villains",
                            Value = 30.74m
                        },
                        new
                        {
                            VinylDiscId = 183,
                            MusicGenreId = 4,
                            Name = "Ted Nugent",
                            Value = 81.06m
                        },
                        new
                        {
                            VinylDiscId = 184,
                            MusicGenreId = 4,
                            Name = "Only By The Night",
                            Value = 29.96m
                        },
                        new
                        {
                            VinylDiscId = 185,
                            MusicGenreId = 4,
                            Name = "Wolfmother",
                            Value = 95.29m
                        },
                        new
                        {
                            VinylDiscId = 186,
                            MusicGenreId = 4,
                            Name = "Moving Pictures (2011 Remaster)",
                            Value = 44.25m
                        },
                        new
                        {
                            VinylDiscId = 187,
                            MusicGenreId = 4,
                            Name = "Silver Side Up",
                            Value = 13.06m
                        },
                        new
                        {
                            VinylDiscId = 188,
                            MusicGenreId = 4,
                            Name = "Marauder",
                            Value = 68.53m
                        },
                        new
                        {
                            VinylDiscId = 189,
                            MusicGenreId = 4,
                            Name = "Disobey",
                            Value = 87.64m
                        },
                        new
                        {
                            VinylDiscId = 190,
                            MusicGenreId = 4,
                            Name = "Something Like Human",
                            Value = 95.24m
                        },
                        new
                        {
                            VinylDiscId = 191,
                            MusicGenreId = 4,
                            Name = "Are You Experienced",
                            Value = 19.80m
                        },
                        new
                        {
                            VinylDiscId = 192,
                            MusicGenreId = 4,
                            Name = "I Don't Want To Miss A Thing",
                            Value = 88.92m
                        },
                        new
                        {
                            VinylDiscId = 193,
                            MusicGenreId = 4,
                            Name = "One More Light",
                            Value = 56.46m
                        },
                        new
                        {
                            VinylDiscId = 194,
                            MusicGenreId = 4,
                            Name = "11 Short Stories of Pain & Glory",
                            Value = 26.49m
                        },
                        new
                        {
                            VinylDiscId = 195,
                            MusicGenreId = 4,
                            Name = "finding it hard to smile",
                            Value = 91.46m
                        },
                        new
                        {
                            VinylDiscId = 196,
                            MusicGenreId = 4,
                            Name = "MANIA",
                            Value = 15.46m
                        },
                        new
                        {
                            VinylDiscId = 197,
                            MusicGenreId = 4,
                            Name = "The Battle Of Los Angeles",
                            Value = 74.97m
                        },
                        new
                        {
                            VinylDiscId = 198,
                            MusicGenreId = 4,
                            Name = "Ten Thousand Fists",
                            Value = 94.68m
                        },
                        new
                        {
                            VinylDiscId = 199,
                            MusicGenreId = 4,
                            Name = "One By One (Expanded Edition)",
                            Value = 58.75m
                        },
                        new
                        {
                            VinylDiscId = 200,
                            MusicGenreId = 4,
                            Name = "Greatest Hits",
                            Value = 36.75m
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ItemSale", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.Sale", "Sale")
                        .WithMany("ItemSales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VinylRecordSale.Domain.Entities.VinylDisc", "VinylDisc")
                        .WithMany("ItemSales")
                        .HasForeignKey("VinylDiscId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Sale", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.VinylDisc", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.MusicGenre", "MusicGenre")
                        .WithMany("VinylDiscs")
                        .HasForeignKey("MusicGenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
