// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinylRecordSale.Infra.Data.Contexts;

namespace VinylRecordSale.Service.Api.Migrations
{
    [DbContext(typeof(ContextEf))]
    [Migration("20191205230147_Migration-Initial")]
    partial class MigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VinylRecordSale")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Email = "pablomoreira79@yahoo.com",
                            FullName = "Pablo Moreira"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "talitaalbuquerque.Macedo@live.com",
                            FullName = "Talita Albuquerque"
                        },
                        new
                        {
                            ClientId = 3,
                            Email = "silviabarros43@live.com",
                            FullName = "Sílvia Barros"
                        },
                        new
                        {
                            ClientId = 4,
                            Email = "dalilamoraes.Oliveira88@bol.com.br",
                            FullName = "Dalila Moraes"
                        },
                        new
                        {
                            ClientId = 5,
                            Email = "cesarmelo.Costa@live.com",
                            FullName = "César Melo"
                        },
                        new
                        {
                            ClientId = 6,
                            Email = "hugomelo41@gmail.com",
                            FullName = "Hugo Melo"
                        },
                        new
                        {
                            ClientId = 7,
                            Email = "kleberalbuquerque.Saraiva90@yahoo.com",
                            FullName = "Kléber Albuquerque"
                        },
                        new
                        {
                            ClientId = 8,
                            Email = "marceloalbuquerque81@hotmail.com",
                            FullName = "Marcelo Albuquerque"
                        },
                        new
                        {
                            ClientId = 9,
                            Email = "antoniosilva_Albuquerque22@live.com",
                            FullName = "Antônio Silva"
                        },
                        new
                        {
                            ClientId = 10,
                            Email = "yagocosta39@gmail.com",
                            FullName = "Yago Costa"
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ConfigCashback", b =>
                {
                    b.Property<int>("MusicGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("PercentageFriday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageMonday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageSaturday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageSunday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageThursday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageTuesday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageWednesday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("MusicGenreId");

                    b.ToTable("ConfigCashbacks");

                    b.HasData(
                        new
                        {
                            MusicGenreId = 1,
                            PercentageFriday = 15m,
                            PercentageMonday = 7m,
                            PercentageSaturday = 20m,
                            PercentageSunday = 25m,
                            PercentageThursday = 10m,
                            PercentageTuesday = 6m,
                            PercentageWednesday = 2m
                        },
                        new
                        {
                            MusicGenreId = 2,
                            PercentageFriday = 25m,
                            PercentageMonday = 5m,
                            PercentageSaturday = 30m,
                            PercentageSunday = 30m,
                            PercentageThursday = 20m,
                            PercentageTuesday = 10m,
                            PercentageWednesday = 15m
                        },
                        new
                        {
                            MusicGenreId = 3,
                            PercentageFriday = 18m,
                            PercentageMonday = 3m,
                            PercentageSaturday = 25m,
                            PercentageSunday = 35m,
                            PercentageThursday = 13m,
                            PercentageTuesday = 5m,
                            PercentageWednesday = 8m
                        },
                        new
                        {
                            MusicGenreId = 4,
                            PercentageFriday = 20m,
                            PercentageMonday = 10m,
                            PercentageSaturday = 40m,
                            PercentageSunday = 40m,
                            PercentageThursday = 15m,
                            PercentageTuesday = 15m,
                            PercentageWednesday = 15m
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ItemSale", b =>
                {
                    b.Property<int>("ItemSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cashback")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VinylDiscId")
                        .HasColumnType("int");

                    b.HasKey("ItemSaleId");

                    b.HasIndex("SaleId");

                    b.HasIndex("VinylDiscId");

                    b.ToTable("ItemSales");
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.MusicGenre", b =>
                {
                    b.Property<int>("MusicGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MusicGenreId");

                    b.ToTable("MusicGenres");

                    b.HasData(
                        new
                        {
                            MusicGenreId = 1,
                            Description = "Pop"
                        },
                        new
                        {
                            MusicGenreId = 2,
                            Description = "Mpb"
                        },
                        new
                        {
                            MusicGenreId = 3,
                            Description = "Classic"
                        },
                        new
                        {
                            MusicGenreId = 4,
                            Description = "Rock"
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CashbackTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("ClientId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.VinylDisc", b =>
                {
                    b.Property<int>("VinylDiscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MusicGenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("VinylDiscId");

                    b.HasIndex("MusicGenreId");

                    b.ToTable("VinylDiscs");

                    b.HasData(
                        new
                        {
                            VinylDiscId = 1,
                            MusicGenreId = 1,
                            Name = "Playboi Carti",
                            Value = 78.74m
                        },
                        new
                        {
                            VinylDiscId = 2,
                            MusicGenreId = 1,
                            Name = "Lust For Life",
                            Value = 85.98m
                        },
                        new
                        {
                            VinylDiscId = 3,
                            MusicGenreId = 1,
                            Name = "5 Seconds Of Summer",
                            Value = 50.84m
                        },
                        new
                        {
                            VinylDiscId = 4,
                            MusicGenreId = 1,
                            Name = "Only Way Is Up (Deluxe)",
                            Value = 95.07m
                        },
                        new
                        {
                            VinylDiscId = 5,
                            MusicGenreId = 1,
                            Name = "Love Someone",
                            Value = 33.26m
                        },
                        new
                        {
                            VinylDiscId = 6,
                            MusicGenreId = 1,
                            Name = "Deadroses",
                            Value = 79.21m
                        },
                        new
                        {
                            VinylDiscId = 7,
                            MusicGenreId = 1,
                            Name = "Blonde",
                            Value = 24.30m
                        },
                        new
                        {
                            VinylDiscId = 8,
                            MusicGenreId = 1,
                            Name = "7/27 (Deluxe)",
                            Value = 70.49m
                        },
                        new
                        {
                            VinylDiscId = 9,
                            MusicGenreId = 1,
                            Name = "9",
                            Value = 87.28m
                        },
                        new
                        {
                            VinylDiscId = 10,
                            MusicGenreId = 1,
                            Name = "The Mack",
                            Value = 80.83m
                        },
                        new
                        {
                            VinylDiscId = 11,
                            MusicGenreId = 1,
                            Name = "Just Hold On",
                            Value = 61.90m
                        },
                        new
                        {
                            VinylDiscId = 12,
                            MusicGenreId = 1,
                            Name = "A Town Called Paradise",
                            Value = 80.08m
                        },
                        new
                        {
                            VinylDiscId = 13,
                            MusicGenreId = 1,
                            Name = "All My Friends (feat. Tinashe & Chance the Rapper)",
                            Value = 73.67m
                        },
                        new
                        {
                            VinylDiscId = 14,
                            MusicGenreId = 1,
                            Name = "Glory Days: The Platinum Edition",
                            Value = 98.20m
                        },
                        new
                        {
                            VinylDiscId = 15,
                            MusicGenreId = 1,
                            Name = "digital druglord",
                            Value = 84.67m
                        },
                        new
                        {
                            VinylDiscId = 16,
                            MusicGenreId = 1,
                            Name = "Heathens",
                            Value = 62.04m
                        },
                        new
                        {
                            VinylDiscId = 17,
                            MusicGenreId = 1,
                            Name = "Happier",
                            Value = 30.43m
                        },
                        new
                        {
                            VinylDiscId = 18,
                            MusicGenreId = 1,
                            Name = "Melodrama",
                            Value = 35.11m
                        },
                        new
                        {
                            VinylDiscId = 19,
                            MusicGenreId = 1,
                            Name = "I Cry When I Laugh",
                            Value = 34.35m
                        },
                        new
                        {
                            VinylDiscId = 20,
                            MusicGenreId = 1,
                            Name = "Oh My My (Deluxe)",
                            Value = 17.19m
                        },
                        new
                        {
                            VinylDiscId = 21,
                            MusicGenreId = 1,
                            Name = "Bangerz (Deluxe Version)",
                            Value = 88.21m
                        },
                        new
                        {
                            VinylDiscId = 22,
                            MusicGenreId = 1,
                            Name = "Red Pill Blues (Deluxe)",
                            Value = 64.66m
                        },
                        new
                        {
                            VinylDiscId = 23,
                            MusicGenreId = 1,
                            Name = "Promises (with Sam Smith)",
                            Value = 52.22m
                        },
                        new
                        {
                            VinylDiscId = 24,
                            MusicGenreId = 1,
                            Name = "The Beautiful & Damned",
                            Value = 94.29m
                        },
                        new
                        {
                            VinylDiscId = 25,
                            MusicGenreId = 1,
                            Name = "So Good",
                            Value = 49.80m
                        },
                        new
                        {
                            VinylDiscId = 26,
                            MusicGenreId = 1,
                            Name = "The Color Of You",
                            Value = 49.87m
                        },
                        new
                        {
                            VinylDiscId = 27,
                            MusicGenreId = 1,
                            Name = "Handwritten",
                            Value = 33.50m
                        },
                        new
                        {
                            VinylDiscId = 28,
                            MusicGenreId = 1,
                            Name = "÷ (Deluxe)",
                            Value = 90.79m
                        },
                        new
                        {
                            VinylDiscId = 29,
                            MusicGenreId = 1,
                            Name = "HNDRXX",
                            Value = 32.79m
                        },
                        new
                        {
                            VinylDiscId = 30,
                            MusicGenreId = 1,
                            Name = "Major Lazer Essentials",
                            Value = 59.63m
                        },
                        new
                        {
                            VinylDiscId = 31,
                            MusicGenreId = 1,
                            Name = "The Human Condition",
                            Value = 30.99m
                        },
                        new
                        {
                            VinylDiscId = 32,
                            MusicGenreId = 1,
                            Name = "Oh Lord",
                            Value = 77.12m
                        },
                        new
                        {
                            VinylDiscId = 33,
                            MusicGenreId = 1,
                            Name = "The 1975",
                            Value = 68.82m
                        },
                        new
                        {
                            VinylDiscId = 34,
                            MusicGenreId = 1,
                            Name = "Lukas Graham",
                            Value = 33.72m
                        },
                        new
                        {
                            VinylDiscId = 35,
                            MusicGenreId = 1,
                            Name = "bloom",
                            Value = 44.49m
                        },
                        new
                        {
                            VinylDiscId = 36,
                            MusicGenreId = 1,
                            Name = "Calypso",
                            Value = 70.22m
                        },
                        new
                        {
                            VinylDiscId = 37,
                            MusicGenreId = 1,
                            Name = "So Good",
                            Value = 34.87m
                        },
                        new
                        {
                            VinylDiscId = 38,
                            MusicGenreId = 1,
                            Name = "Blank Face LP",
                            Value = 43.51m
                        },
                        new
                        {
                            VinylDiscId = 39,
                            MusicGenreId = 1,
                            Name = "Magna Carta... Holy Grail",
                            Value = 39.53m
                        },
                        new
                        {
                            VinylDiscId = 40,
                            MusicGenreId = 1,
                            Name = "SweetSexySavage (Deluxe)",
                            Value = 72.36m
                        },
                        new
                        {
                            VinylDiscId = 41,
                            MusicGenreId = 1,
                            Name = "Culture",
                            Value = 65.78m
                        },
                        new
                        {
                            VinylDiscId = 42,
                            MusicGenreId = 1,
                            Name = "Flicker (Deluxe)",
                            Value = 94.50m
                        },
                        new
                        {
                            VinylDiscId = 43,
                            MusicGenreId = 1,
                            Name = "The Thrill Of It All (Special Edition)",
                            Value = 32.82m
                        },
                        new
                        {
                            VinylDiscId = 44,
                            MusicGenreId = 1,
                            Name = "AVĪCI (01)",
                            Value = 99.65m
                        },
                        new
                        {
                            VinylDiscId = 45,
                            MusicGenreId = 1,
                            Name = "Whole Heart",
                            Value = 51.49m
                        },
                        new
                        {
                            VinylDiscId = 46,
                            MusicGenreId = 1,
                            Name = "Lil Uzi Vert vs. The World",
                            Value = 79.52m
                        },
                        new
                        {
                            VinylDiscId = 47,
                            MusicGenreId = 1,
                            Name = "Silence",
                            Value = 16.55m
                        },
                        new
                        {
                            VinylDiscId = 48,
                            MusicGenreId = 1,
                            Name = "Kamikaze",
                            Value = 39.43m
                        },
                        new
                        {
                            VinylDiscId = 49,
                            MusicGenreId = 1,
                            Name = "Tell Me You Love Me (Deluxe)",
                            Value = 81.24m
                        },
                        new
                        {
                            VinylDiscId = 50,
                            MusicGenreId = 1,
                            Name = "My House",
                            Value = 13.00m
                        },
                        new
                        {
                            VinylDiscId = 51,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 20.67m
                        },
                        new
                        {
                            VinylDiscId = 52,
                            MusicGenreId = 2,
                            Name = "I Love MPB - O Nosso Amor A Gente Inventa",
                            Value = 75.65m
                        },
                        new
                        {
                            VinylDiscId = 53,
                            MusicGenreId = 2,
                            Name = "Multishow Ao Vivo Ana Carolina \"Dois Quartos\"",
                            Value = 91.13m
                        },
                        new
                        {
                            VinylDiscId = 54,
                            MusicGenreId = 2,
                            Name = "Brasis",
                            Value = 49.06m
                        },
                        new
                        {
                            VinylDiscId = 55,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 28.99m
                        },
                        new
                        {
                            VinylDiscId = 56,
                            MusicGenreId = 2,
                            Name = "Volta",
                            Value = 24.98m
                        },
                        new
                        {
                            VinylDiscId = 57,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 44.66m
                        },
                        new
                        {
                            VinylDiscId = 58,
                            MusicGenreId = 2,
                            Name = "Amado Batista \"85\"",
                            Value = 56.45m
                        },
                        new
                        {
                            VinylDiscId = 59,
                            MusicGenreId = 2,
                            Name = "Sinais dos Tempos",
                            Value = 56.17m
                        },
                        new
                        {
                            VinylDiscId = 60,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 83.29m
                        },
                        new
                        {
                            VinylDiscId = 61,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 56.61m
                        },
                        new
                        {
                            VinylDiscId = 62,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 33.41m
                        },
                        new
                        {
                            VinylDiscId = 63,
                            MusicGenreId = 2,
                            Name = "Toni Ferreira",
                            Value = 48.60m
                        },
                        new
                        {
                            VinylDiscId = 64,
                            MusicGenreId = 2,
                            Name = "Geraldo Azevedo",
                            Value = 38.56m
                        },
                        new
                        {
                            VinylDiscId = 65,
                            MusicGenreId = 2,
                            Name = "Acabou Chorare",
                            Value = 60.75m
                        },
                        new
                        {
                            VinylDiscId = 66,
                            MusicGenreId = 2,
                            Name = "Volta",
                            Value = 84.69m
                        },
                        new
                        {
                            VinylDiscId = 67,
                            MusicGenreId = 2,
                            Name = "De Lá Até Aqui",
                            Value = 22.16m
                        },
                        new
                        {
                            VinylDiscId = 68,
                            MusicGenreId = 2,
                            Name = "Meu Coração Não Quer Viver Batendo Devagar",
                            Value = 50.86m
                        },
                        new
                        {
                            VinylDiscId = 69,
                            MusicGenreId = 2,
                            Name = "Sinais dos Tempos",
                            Value = 64.62m
                        },
                        new
                        {
                            VinylDiscId = 70,
                            MusicGenreId = 2,
                            Name = "Vanessa da Mata canta Tom Jobim (Deluxe Edition)",
                            Value = 25.35m
                        },
                        new
                        {
                            VinylDiscId = 71,
                            MusicGenreId = 2,
                            Name = "Fôlego",
                            Value = 38.08m
                        },
                        new
                        {
                            VinylDiscId = 72,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 86.82m
                        },
                        new
                        {
                            VinylDiscId = 73,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 95.48m
                        },
                        new
                        {
                            VinylDiscId = 74,
                            MusicGenreId = 2,
                            Name = "Recanto",
                            Value = 61.89m
                        },
                        new
                        {
                            VinylDiscId = 75,
                            MusicGenreId = 2,
                            Name = "Brasis",
                            Value = 51.31m
                        },
                        new
                        {
                            VinylDiscId = 76,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 93.61m
                        },
                        new
                        {
                            VinylDiscId = 77,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 42.74m
                        },
                        new
                        {
                            VinylDiscId = 78,
                            MusicGenreId = 2,
                            Name = "É Proibido Fumar (Remasterizado)",
                            Value = 52.47m
                        },
                        new
                        {
                            VinylDiscId = 79,
                            MusicGenreId = 2,
                            Name = "De Lá Até Aqui",
                            Value = 53.70m
                        },
                        new
                        {
                            VinylDiscId = 80,
                            MusicGenreId = 2,
                            Name = "Meu Coração Não Quer Viver Batendo Devagar",
                            Value = 70.17m
                        },
                        new
                        {
                            VinylDiscId = 81,
                            MusicGenreId = 2,
                            Name = "O Micróbio do Samba",
                            Value = 44.22m
                        },
                        new
                        {
                            VinylDiscId = 82,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 93.97m
                        },
                        new
                        {
                            VinylDiscId = 83,
                            MusicGenreId = 2,
                            Name = "Geraldo Azevedo",
                            Value = 20.45m
                        },
                        new
                        {
                            VinylDiscId = 84,
                            MusicGenreId = 2,
                            Name = "Recanto",
                            Value = 30.70m
                        },
                        new
                        {
                            VinylDiscId = 85,
                            MusicGenreId = 2,
                            Name = "Volta",
                            Value = 49.86m
                        },
                        new
                        {
                            VinylDiscId = 86,
                            MusicGenreId = 2,
                            Name = "Acabou Chorare",
                            Value = 55.24m
                        },
                        new
                        {
                            VinylDiscId = 87,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 85.88m
                        },
                        new
                        {
                            VinylDiscId = 88,
                            MusicGenreId = 2,
                            Name = "Ana Car9lina+um",
                            Value = 30.66m
                        },
                        new
                        {
                            VinylDiscId = 89,
                            MusicGenreId = 2,
                            Name = "Musica do Brasil Antonio Carlos Jobim \"Romántico\"",
                            Value = 15.63m
                        },
                        new
                        {
                            VinylDiscId = 90,
                            MusicGenreId = 2,
                            Name = "Toni Ferreira",
                            Value = 30.41m
                        },
                        new
                        {
                            VinylDiscId = 91,
                            MusicGenreId = 2,
                            Name = "Roupa Nova",
                            Value = 36.46m
                        },
                        new
                        {
                            VinylDiscId = 92,
                            MusicGenreId = 2,
                            Name = "Acabou Chorare",
                            Value = 78.32m
                        },
                        new
                        {
                            VinylDiscId = 93,
                            MusicGenreId = 2,
                            Name = "Vanessa da Mata canta Tom Jobim (Deluxe Edition)",
                            Value = 87.24m
                        },
                        new
                        {
                            VinylDiscId = 94,
                            MusicGenreId = 2,
                            Name = "Fôlego",
                            Value = 56.13m
                        },
                        new
                        {
                            VinylDiscId = 95,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 26.65m
                        },
                        new
                        {
                            VinylDiscId = 96,
                            MusicGenreId = 2,
                            Name = "O Descobridor Dos Sete Mares",
                            Value = 43.27m
                        },
                        new
                        {
                            VinylDiscId = 97,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 56.81m
                        },
                        new
                        {
                            VinylDiscId = 98,
                            MusicGenreId = 2,
                            Name = "Seu Jorge and Almaz",
                            Value = 94.16m
                        },
                        new
                        {
                            VinylDiscId = 99,
                            MusicGenreId = 2,
                            Name = "De Lá Até Aqui",
                            Value = 49.80m
                        },
                        new
                        {
                            VinylDiscId = 100,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 66.70m
                        },
                        new
                        {
                            VinylDiscId = 101,
                            MusicGenreId = 3,
                            Name = "Faure: Requiem, Op. 48 / Pavane, Op. 50",
                            Value = 68.26m
                        },
                        new
                        {
                            VinylDiscId = 102,
                            MusicGenreId = 3,
                            Name = "Spectacular",
                            Value = 65.59m
                        },
                        new
                        {
                            VinylDiscId = 103,
                            MusicGenreId = 3,
                            Name = "Dance Of The Blessed Spirits",
                            Value = 74.71m
                        },
                        new
                        {
                            VinylDiscId = 104,
                            MusicGenreId = 3,
                            Name = "V For Vendetta (Music From The Motion Picture)",
                            Value = 66.79m
                        },
                        new
                        {
                            VinylDiscId = 105,
                            MusicGenreId = 3,
                            Name = "Mahler, A.: 5 Lieder / 5 Gesange / 4 Lieder",
                            Value = 74.82m
                        },
                        new
                        {
                            VinylDiscId = 106,
                            MusicGenreId = 3,
                            Name = "Hugo Original Score",
                            Value = 33.75m
                        },
                        new
                        {
                            VinylDiscId = 107,
                            MusicGenreId = 3,
                            Name = "Schumann: Violin Concerto",
                            Value = 80.07m
                        },
                        new
                        {
                            VinylDiscId = 108,
                            MusicGenreId = 3,
                            Name = "Yellow Lounge",
                            Value = 40.14m
                        },
                        new
                        {
                            VinylDiscId = 109,
                            MusicGenreId = 3,
                            Name = "Prokofiev: Romeo and Juliet",
                            Value = 97.65m
                        },
                        new
                        {
                            VinylDiscId = 110,
                            MusicGenreId = 3,
                            Name = "Book of Leaves",
                            Value = 35.29m
                        },
                        new
                        {
                            VinylDiscId = 111,
                            MusicGenreId = 3,
                            Name = "Tchaikovsky: The Nutcracker (Standard Version)",
                            Value = 82.13m
                        },
                        new
                        {
                            VinylDiscId = 112,
                            MusicGenreId = 3,
                            Name = "Klassik ohne Krise: Grandioser Gesang",
                            Value = 92.09m
                        },
                        new
                        {
                            VinylDiscId = 113,
                            MusicGenreId = 3,
                            Name = "Sunrise of the Planetary Dream Collector",
                            Value = 13.65m
                        },
                        new
                        {
                            VinylDiscId = 114,
                            MusicGenreId = 3,
                            Name = "Copland Conducts Copland - Expanded Edition (Fanfare for the Common Man, Appalachian Spring, Old American Songs (Complete), Rodeo: Four Dance Episodes)",
                            Value = 85.90m
                        },
                        new
                        {
                            VinylDiscId = 115,
                            MusicGenreId = 3,
                            Name = "La Voce del Violoncello",
                            Value = 49.98m
                        },
                        new
                        {
                            VinylDiscId = 116,
                            MusicGenreId = 3,
                            Name = "Mozart: Piano Sonatas K.309, K.332 & K.570",
                            Value = 62.54m
                        },
                        new
                        {
                            VinylDiscId = 117,
                            MusicGenreId = 3,
                            Name = "Xenakis, I.: Orchestral Works, Vol. 5 - Metastaseis / Pithoprakta / St/48 / Achorripsis / Syrmos / Hiketides Suite",
                            Value = 23.86m
                        },
                        new
                        {
                            VinylDiscId = 118,
                            MusicGenreId = 3,
                            Name = "Tintomara",
                            Value = 28.80m
                        },
                        new
                        {
                            VinylDiscId = 119,
                            MusicGenreId = 3,
                            Name = "The Piano: Music From The Motion Picture",
                            Value = 88.60m
                        },
                        new
                        {
                            VinylDiscId = 120,
                            MusicGenreId = 3,
                            Name = "Hope Street Tunnel Blues: Music for Piano By Philip Glass and Alvin Curran",
                            Value = 16.40m
                        },
                        new
                        {
                            VinylDiscId = 121,
                            MusicGenreId = 3,
                            Name = "Szymanowski: Piano Works, Vol. 1",
                            Value = 98.70m
                        },
                        new
                        {
                            VinylDiscId = 122,
                            MusicGenreId = 3,
                            Name = "Time Present And Time Past",
                            Value = 91.40m
                        },
                        new
                        {
                            VinylDiscId = 123,
                            MusicGenreId = 3,
                            Name = "Solipsism",
                            Value = 46.13m
                        },
                        new
                        {
                            VinylDiscId = 124,
                            MusicGenreId = 3,
                            Name = "Jane Eyre - Original Motion Picture Soundtrack",
                            Value = 45.10m
                        },
                        new
                        {
                            VinylDiscId = 125,
                            MusicGenreId = 3,
                            Name = "Messiaen: Preludes / 4 Rhythmic Studies / Canteyodjaya",
                            Value = 88.79m
                        },
                        new
                        {
                            VinylDiscId = 126,
                            MusicGenreId = 3,
                            Name = "Pops Britannia",
                            Value = 59.66m
                        },
                        new
                        {
                            VinylDiscId = 127,
                            MusicGenreId = 3,
                            Name = "Bizet (The Best Of)",
                            Value = 99.48m
                        },
                        new
                        {
                            VinylDiscId = 128,
                            MusicGenreId = 3,
                            Name = "Strauss: Die Fledermaus",
                            Value = 50.25m
                        },
                        new
                        {
                            VinylDiscId = 129,
                            MusicGenreId = 3,
                            Name = "Ravel : Orchestral works",
                            Value = 46.14m
                        },
                        new
                        {
                            VinylDiscId = 130,
                            MusicGenreId = 3,
                            Name = "The Good, The Bad & The Ugly (Original Motion Picture Soundtrack)",
                            Value = 18.94m
                        },
                        new
                        {
                            VinylDiscId = 131,
                            MusicGenreId = 3,
                            Name = "Romantic Favorites for Strings (Expanded Edition)",
                            Value = 47.70m
                        },
                        new
                        {
                            VinylDiscId = 132,
                            MusicGenreId = 3,
                            Name = "Time Curve: Music for Piano by Philip Glass and William Duckworth",
                            Value = 48.48m
                        },
                        new
                        {
                            VinylDiscId = 133,
                            MusicGenreId = 3,
                            Name = "Living Room Songs",
                            Value = 13.57m
                        },
                        new
                        {
                            VinylDiscId = 134,
                            MusicGenreId = 3,
                            Name = "Sibelius: Pelleas and Melisande Suite, Musik zu einer Szene & 3 Pièces pour orchestre",
                            Value = 86.90m
                        },
                        new
                        {
                            VinylDiscId = 135,
                            MusicGenreId = 3,
                            Name = "Monteverdi: Vespers of 1610",
                            Value = 12.82m
                        },
                        new
                        {
                            VinylDiscId = 136,
                            MusicGenreId = 3,
                            Name = "Tchaikovsky: Swan Lake",
                            Value = 78.52m
                        },
                        new
                        {
                            VinylDiscId = 137,
                            MusicGenreId = 3,
                            Name = "Bruckner: Motets",
                            Value = 30.16m
                        },
                        new
                        {
                            VinylDiscId = 138,
                            MusicGenreId = 3,
                            Name = "Satie: Avant-dernières pensées (Bonus Track Version)",
                            Value = 53.56m
                        },
                        new
                        {
                            VinylDiscId = 139,
                            MusicGenreId = 3,
                            Name = "Horowitz Plays Liszt",
                            Value = 55.78m
                        },
                        new
                        {
                            VinylDiscId = 140,
                            MusicGenreId = 3,
                            Name = "Beethoven, Period.",
                            Value = 27.01m
                        },
                        new
                        {
                            VinylDiscId = 141,
                            MusicGenreId = 3,
                            Name = "Hindemith: Mathis Der Maler / Symphonic Metamorphosis",
                            Value = 75.08m
                        },
                        new
                        {
                            VinylDiscId = 142,
                            MusicGenreId = 3,
                            Name = "Dvořák: Symphony No. 9 \"New World\" - Varèse: Amériques (Live)",
                            Value = 56.64m
                        },
                        new
                        {
                            VinylDiscId = 143,
                            MusicGenreId = 3,
                            Name = "Mussorgsky: Pictures at an Exhibition - Expanded Edition",
                            Value = 32.91m
                        },
                        new
                        {
                            VinylDiscId = 144,
                            MusicGenreId = 3,
                            Name = "My Favorite Liszt",
                            Value = 80.24m
                        },
                        new
                        {
                            VinylDiscId = 145,
                            MusicGenreId = 3,
                            Name = "In 27 Pieces: the Hilary Hahn Encores",
                            Value = 48.18m
                        },
                        new
                        {
                            VinylDiscId = 146,
                            MusicGenreId = 3,
                            Name = "In a Landscape: Piano Music of John Cage",
                            Value = 44.27m
                        },
                        new
                        {
                            VinylDiscId = 147,
                            MusicGenreId = 3,
                            Name = "Without Sinking",
                            Value = 75.57m
                        },
                        new
                        {
                            VinylDiscId = 148,
                            MusicGenreId = 3,
                            Name = "Ralph Vaughan Williams & James MacMillan: Oboe Concertos",
                            Value = 12.24m
                        },
                        new
                        {
                            VinylDiscId = 149,
                            MusicGenreId = 3,
                            Name = "Christopher Tye: Latin & English Church Music",
                            Value = 17.06m
                        },
                        new
                        {
                            VinylDiscId = 150,
                            MusicGenreId = 3,
                            Name = "Handel Sarabande",
                            Value = 64.02m
                        },
                        new
                        {
                            VinylDiscId = 151,
                            MusicGenreId = 4,
                            Name = "Good Thing",
                            Value = 30.31m
                        },
                        new
                        {
                            VinylDiscId = 152,
                            MusicGenreId = 4,
                            Name = "11 Short Stories of Pain & Glory",
                            Value = 38.91m
                        },
                        new
                        {
                            VinylDiscId = 153,
                            MusicGenreId = 4,
                            Name = "5",
                            Value = 16.46m
                        },
                        new
                        {
                            VinylDiscId = 154,
                            MusicGenreId = 4,
                            Name = "Vivid (Expanded Edition)",
                            Value = 44.30m
                        },
                        new
                        {
                            VinylDiscId = 155,
                            MusicGenreId = 4,
                            Name = "Don't You Worry, Honey",
                            Value = 67.90m
                        },
                        new
                        {
                            VinylDiscId = 156,
                            MusicGenreId = 4,
                            Name = "The Boy Who Died Wolf",
                            Value = 76.76m
                        },
                        new
                        {
                            VinylDiscId = 157,
                            MusicGenreId = 4,
                            Name = "Are You Experienced",
                            Value = 30.36m
                        },
                        new
                        {
                            VinylDiscId = 158,
                            MusicGenreId = 4,
                            Name = "in•ter a•li•a",
                            Value = 40.51m
                        },
                        new
                        {
                            VinylDiscId = 159,
                            MusicGenreId = 4,
                            Name = "Charm City",
                            Value = 77.90m
                        },
                        new
                        {
                            VinylDiscId = 160,
                            MusicGenreId = 4,
                            Name = "The Atlas Underground",
                            Value = 26.06m
                        },
                        new
                        {
                            VinylDiscId = 161,
                            MusicGenreId = 4,
                            Name = "How To Be A Human Being",
                            Value = 34.17m
                        },
                        new
                        {
                            VinylDiscId = 162,
                            MusicGenreId = 4,
                            Name = "Word Up! (The Remixes)",
                            Value = 40.72m
                        },
                        new
                        {
                            VinylDiscId = 163,
                            MusicGenreId = 4,
                            Name = "Strange Days",
                            Value = 93.90m
                        },
                        new
                        {
                            VinylDiscId = 164,
                            MusicGenreId = 4,
                            Name = "The Sound of Madness (International)",
                            Value = 89.61m
                        },
                        new
                        {
                            VinylDiscId = 165,
                            MusicGenreId = 4,
                            Name = "Moving Pictures (2011 Remaster)",
                            Value = 87.49m
                        },
                        new
                        {
                            VinylDiscId = 166,
                            MusicGenreId = 4,
                            Name = "Lovely Little Lonely",
                            Value = 44.55m
                        },
                        new
                        {
                            VinylDiscId = 167,
                            MusicGenreId = 4,
                            Name = "Wolfmother",
                            Value = 89.43m
                        },
                        new
                        {
                            VinylDiscId = 168,
                            MusicGenreId = 4,
                            Name = "Crazy World",
                            Value = 26.64m
                        },
                        new
                        {
                            VinylDiscId = 169,
                            MusicGenreId = 4,
                            Name = "Every Six Seconds",
                            Value = 83.98m
                        },
                        new
                        {
                            VinylDiscId = 170,
                            MusicGenreId = 4,
                            Name = "UP",
                            Value = 71.35m
                        },
                        new
                        {
                            VinylDiscId = 171,
                            MusicGenreId = 4,
                            Name = "Vitalogy",
                            Value = 43.28m
                        },
                        new
                        {
                            VinylDiscId = 172,
                            MusicGenreId = 4,
                            Name = "Come What(ever) May [10th Anniversary Edition]",
                            Value = 70.20m
                        },
                        new
                        {
                            VinylDiscId = 173,
                            MusicGenreId = 4,
                            Name = "Quarter Past Midnight",
                            Value = 72.92m
                        },
                        new
                        {
                            VinylDiscId = 174,
                            MusicGenreId = 4,
                            Name = "Anon.",
                            Value = 72.50m
                        },
                        new
                        {
                            VinylDiscId = 175,
                            MusicGenreId = 4,
                            Name = "MOSAIC",
                            Value = 41.23m
                        },
                        new
                        {
                            VinylDiscId = 176,
                            MusicGenreId = 4,
                            Name = "The Attractions Of Youth",
                            Value = 52.96m
                        },
                        new
                        {
                            VinylDiscId = 177,
                            MusicGenreId = 4,
                            Name = "Straight Shooter",
                            Value = 69.39m
                        },
                        new
                        {
                            VinylDiscId = 178,
                            MusicGenreId = 4,
                            Name = "Can't Knock The Hustle",
                            Value = 65.79m
                        },
                        new
                        {
                            VinylDiscId = 179,
                            MusicGenreId = 4,
                            Name = "World Away",
                            Value = 96.82m
                        },
                        new
                        {
                            VinylDiscId = 180,
                            MusicGenreId = 4,
                            Name = "Feed the Machine",
                            Value = 55.42m
                        },
                        new
                        {
                            VinylDiscId = 181,
                            MusicGenreId = 4,
                            Name = "Simulation Theory (Super Deluxe)",
                            Value = 83.99m
                        },
                        new
                        {
                            VinylDiscId = 182,
                            MusicGenreId = 4,
                            Name = "A Fever You Can't Sweat Out",
                            Value = 98.14m
                        },
                        new
                        {
                            VinylDiscId = 183,
                            MusicGenreId = 4,
                            Name = "Are You Experienced",
                            Value = 44.10m
                        },
                        new
                        {
                            VinylDiscId = 184,
                            MusicGenreId = 4,
                            Name = "Rebel Yell",
                            Value = 82.02m
                        },
                        new
                        {
                            VinylDiscId = 185,
                            MusicGenreId = 4,
                            Name = "Rumours",
                            Value = 88.52m
                        },
                        new
                        {
                            VinylDiscId = 186,
                            MusicGenreId = 4,
                            Name = "Blood Sugar Sex Magik (Deluxe Edition)",
                            Value = 19.69m
                        },
                        new
                        {
                            VinylDiscId = 187,
                            MusicGenreId = 4,
                            Name = "Anthology",
                            Value = 42.92m
                        },
                        new
                        {
                            VinylDiscId = 188,
                            MusicGenreId = 4,
                            Name = "Weathered",
                            Value = 69.17m
                        },
                        new
                        {
                            VinylDiscId = 189,
                            MusicGenreId = 4,
                            Name = "Slippery When Wet",
                            Value = 29.90m
                        },
                        new
                        {
                            VinylDiscId = 190,
                            MusicGenreId = 4,
                            Name = "For Crying Out Loud (Deluxe)",
                            Value = 35.96m
                        },
                        new
                        {
                            VinylDiscId = 191,
                            MusicGenreId = 4,
                            Name = "Around the Fur",
                            Value = 59.06m
                        },
                        new
                        {
                            VinylDiscId = 192,
                            MusicGenreId = 4,
                            Name = "The Better Life",
                            Value = 89.55m
                        },
                        new
                        {
                            VinylDiscId = 193,
                            MusicGenreId = 4,
                            Name = "Blur [Special Edition]",
                            Value = 75.56m
                        },
                        new
                        {
                            VinylDiscId = 194,
                            MusicGenreId = 4,
                            Name = "Nevermind (Deluxe Edition)",
                            Value = 40.61m
                        },
                        new
                        {
                            VinylDiscId = 195,
                            MusicGenreId = 4,
                            Name = "Wired",
                            Value = 92.74m
                        },
                        new
                        {
                            VinylDiscId = 196,
                            MusicGenreId = 4,
                            Name = "Home of the Strange",
                            Value = 45.26m
                        },
                        new
                        {
                            VinylDiscId = 197,
                            MusicGenreId = 4,
                            Name = "And Justice for None (Deluxe)",
                            Value = 62.64m
                        },
                        new
                        {
                            VinylDiscId = 198,
                            MusicGenreId = 4,
                            Name = "Billy Talent II",
                            Value = 43.20m
                        },
                        new
                        {
                            VinylDiscId = 199,
                            MusicGenreId = 4,
                            Name = "Hail to the King",
                            Value = 92.65m
                        },
                        new
                        {
                            VinylDiscId = 200,
                            MusicGenreId = 4,
                            Name = "Ted Nugent",
                            Value = 14.53m
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ItemSale", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.Sale", "Sale")
                        .WithMany("ItemSales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VinylRecordSale.Domain.Entities.VinylDisc", "VinylDisc")
                        .WithMany("ItemSales")
                        .HasForeignKey("VinylDiscId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Sale", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.VinylDisc", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.MusicGenre", "MusicGenre")
                        .WithMany("VinylDiscs")
                        .HasForeignKey("MusicGenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
