// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinylRecordSale.Infra.Data.Contexts;

namespace VinylRecordSale.Service.Api.Migrations
{
    [DbContext(typeof(ContextEf))]
    partial class ContextEfModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VinylRecordSale")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Email = "ricardobarros_Pereira@live.com",
                            FullName = "Ricardo Barros"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "yurimoraes.Batista23@bol.com.br",
                            FullName = "Yuri Moraes"
                        },
                        new
                        {
                            ClientId = 3,
                            Email = "estherbraga.Saraiva64@hotmail.com",
                            FullName = "Esther Braga"
                        },
                        new
                        {
                            ClientId = 4,
                            Email = "merciaoliveira_Melo@yahoo.com",
                            FullName = "Mércia Oliveira"
                        },
                        new
                        {
                            ClientId = 5,
                            Email = "marcelobatista_Moraes45@yahoo.com",
                            FullName = "Marcelo Batista"
                        },
                        new
                        {
                            ClientId = 6,
                            Email = "eduardobraga.Reis@yahoo.com",
                            FullName = "Eduardo Braga"
                        },
                        new
                        {
                            ClientId = 7,
                            Email = "alessandrareis16@gmail.com",
                            FullName = "Alessandra Reis"
                        },
                        new
                        {
                            ClientId = 8,
                            Email = "suelensilva55@live.com",
                            FullName = "Suélen Silva"
                        },
                        new
                        {
                            ClientId = 9,
                            Email = "ceciliacarvalho.Xavier97@gmail.com",
                            FullName = "Cecília Carvalho"
                        },
                        new
                        {
                            ClientId = 10,
                            Email = "brenomartins42@yahoo.com",
                            FullName = "Breno Martins"
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ConfigCashback", b =>
                {
                    b.Property<int>("MusicGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("PercentageFriday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageMonday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageSaturday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageSunday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageThursday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageTuesday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PercentageWednesday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("MusicGenreId");

                    b.ToTable("ConfigCashbacks");

                    b.HasData(
                        new
                        {
                            MusicGenreId = 1,
                            PercentageFriday = 15m,
                            PercentageMonday = 7m,
                            PercentageSaturday = 20m,
                            PercentageSunday = 25m,
                            PercentageThursday = 10m,
                            PercentageTuesday = 6m,
                            PercentageWednesday = 2m
                        },
                        new
                        {
                            MusicGenreId = 2,
                            PercentageFriday = 25m,
                            PercentageMonday = 5m,
                            PercentageSaturday = 30m,
                            PercentageSunday = 30m,
                            PercentageThursday = 20m,
                            PercentageTuesday = 10m,
                            PercentageWednesday = 15m
                        },
                        new
                        {
                            MusicGenreId = 3,
                            PercentageFriday = 18m,
                            PercentageMonday = 3m,
                            PercentageSaturday = 25m,
                            PercentageSunday = 35m,
                            PercentageThursday = 13m,
                            PercentageTuesday = 5m,
                            PercentageWednesday = 8m
                        },
                        new
                        {
                            MusicGenreId = 4,
                            PercentageFriday = 20m,
                            PercentageMonday = 10m,
                            PercentageSaturday = 40m,
                            PercentageSunday = 40m,
                            PercentageThursday = 15m,
                            PercentageTuesday = 15m,
                            PercentageWednesday = 15m
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ItemSale", b =>
                {
                    b.Property<int>("ItemSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cashback")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VinylDiscId")
                        .HasColumnType("int");

                    b.HasKey("ItemSaleId");

                    b.HasIndex("SaleId");

                    b.HasIndex("VinylDiscId");

                    b.ToTable("ItemSales");
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.MusicGenre", b =>
                {
                    b.Property<int>("MusicGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MusicGenreId");

                    b.ToTable("MusicGenres");

                    b.HasData(
                        new
                        {
                            MusicGenreId = 1,
                            Description = "Pop"
                        },
                        new
                        {
                            MusicGenreId = 2,
                            Description = "Mpb"
                        },
                        new
                        {
                            MusicGenreId = 3,
                            Description = "Classic"
                        },
                        new
                        {
                            MusicGenreId = 4,
                            Description = "Rock"
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CashbackTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("ClientId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.VinylDisc", b =>
                {
                    b.Property<int>("VinylDiscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MusicGenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("VinylDiscId");

                    b.HasIndex("MusicGenreId");

                    b.ToTable("VinylDiscs");

                    b.HasData(
                        new
                        {
                            VinylDiscId = 1,
                            MusicGenreId = 1,
                            Name = "Still Got Time",
                            Value = 50.63m
                        },
                        new
                        {
                            VinylDiscId = 2,
                            MusicGenreId = 1,
                            Name = "ANTI (Deluxe)",
                            Value = 30.65m
                        },
                        new
                        {
                            VinylDiscId = 3,
                            MusicGenreId = 1,
                            Name = "Playboi Carti",
                            Value = 34.50m
                        },
                        new
                        {
                            VinylDiscId = 4,
                            MusicGenreId = 1,
                            Name = "Savage Mode",
                            Value = 30.90m
                        },
                        new
                        {
                            VinylDiscId = 5,
                            MusicGenreId = 1,
                            Name = "Blank Face LP",
                            Value = 86.24m
                        },
                        new
                        {
                            VinylDiscId = 6,
                            MusicGenreId = 1,
                            Name = "True",
                            Value = 87.62m
                        },
                        new
                        {
                            VinylDiscId = 7,
                            MusicGenreId = 1,
                            Name = "More Life",
                            Value = 38.71m
                        },
                        new
                        {
                            VinylDiscId = 8,
                            MusicGenreId = 1,
                            Name = "Only You (with Little Mix)",
                            Value = 70.38m
                        },
                        new
                        {
                            VinylDiscId = 9,
                            MusicGenreId = 1,
                            Name = "Culture",
                            Value = 56.68m
                        },
                        new
                        {
                            VinylDiscId = 10,
                            MusicGenreId = 1,
                            Name = "Funk Wav Bounces Vol.1",
                            Value = 35.88m
                        },
                        new
                        {
                            VinylDiscId = 11,
                            MusicGenreId = 1,
                            Name = "From A Distance",
                            Value = 13.12m
                        },
                        new
                        {
                            VinylDiscId = 12,
                            MusicGenreId = 1,
                            Name = "Rodeo (Expanded Edition)",
                            Value = 19.00m
                        },
                        new
                        {
                            VinylDiscId = 13,
                            MusicGenreId = 1,
                            Name = "Still Brazy (Deluxe)",
                            Value = 75.89m
                        },
                        new
                        {
                            VinylDiscId = 14,
                            MusicGenreId = 1,
                            Name = "Trigga Reloaded",
                            Value = 70.33m
                        },
                        new
                        {
                            VinylDiscId = 15,
                            MusicGenreId = 1,
                            Name = "This Is What You Came For",
                            Value = 23.12m
                        },
                        new
                        {
                            VinylDiscId = 16,
                            MusicGenreId = 1,
                            Name = "reputation",
                            Value = 30.52m
                        },
                        new
                        {
                            VinylDiscId = 17,
                            MusicGenreId = 1,
                            Name = "The Bedroom Tour Playlist",
                            Value = 35.71m
                        },
                        new
                        {
                            VinylDiscId = 18,
                            MusicGenreId = 1,
                            Name = "The Good Parts",
                            Value = 79.76m
                        },
                        new
                        {
                            VinylDiscId = 19,
                            MusicGenreId = 1,
                            Name = "EVOL",
                            Value = 54.04m
                        },
                        new
                        {
                            VinylDiscId = 20,
                            MusicGenreId = 1,
                            Name = "Oxymoron (Deluxe)",
                            Value = 61.85m
                        },
                        new
                        {
                            VinylDiscId = 21,
                            MusicGenreId = 1,
                            Name = "This Is America",
                            Value = 33.99m
                        },
                        new
                        {
                            VinylDiscId = 22,
                            MusicGenreId = 1,
                            Name = "Nothing Was The Same (Deluxe)",
                            Value = 77.47m
                        },
                        new
                        {
                            VinylDiscId = 23,
                            MusicGenreId = 1,
                            Name = "Beach House 3",
                            Value = 45.02m
                        },
                        new
                        {
                            VinylDiscId = 24,
                            MusicGenreId = 1,
                            Name = "I Cry When I Laugh",
                            Value = 46.25m
                        },
                        new
                        {
                            VinylDiscId = 25,
                            MusicGenreId = 1,
                            Name = "PARTYNEXTDOOR 3 (P3)",
                            Value = 75.86m
                        },
                        new
                        {
                            VinylDiscId = 26,
                            MusicGenreId = 1,
                            Name = "Made In The A.M. (Deluxe Edition)",
                            Value = 45.53m
                        },
                        new
                        {
                            VinylDiscId = 27,
                            MusicGenreId = 1,
                            Name = "Glory Days: The Platinum Edition",
                            Value = 96.50m
                        },
                        new
                        {
                            VinylDiscId = 28,
                            MusicGenreId = 1,
                            Name = "Morse Code",
                            Value = 58.01m
                        },
                        new
                        {
                            VinylDiscId = 29,
                            MusicGenreId = 1,
                            Name = "Mr. Davis",
                            Value = 74.35m
                        },
                        new
                        {
                            VinylDiscId = 30,
                            MusicGenreId = 1,
                            Name = "Good For You",
                            Value = 45.52m
                        },
                        new
                        {
                            VinylDiscId = 31,
                            MusicGenreId = 1,
                            Name = "Red Pill Blues (Deluxe)",
                            Value = 87.15m
                        },
                        new
                        {
                            VinylDiscId = 32,
                            MusicGenreId = 1,
                            Name = "VHS",
                            Value = 54.08m
                        },
                        new
                        {
                            VinylDiscId = 33,
                            MusicGenreId = 1,
                            Name = "x (Deluxe Edition)",
                            Value = 31.13m
                        },
                        new
                        {
                            VinylDiscId = 34,
                            MusicGenreId = 1,
                            Name = "Waves (Robin Schulz Radio Edit)",
                            Value = 95.27m
                        },
                        new
                        {
                            VinylDiscId = 35,
                            MusicGenreId = 1,
                            Name = "Party's Over",
                            Value = 89.08m
                        },
                        new
                        {
                            VinylDiscId = 36,
                            MusicGenreId = 1,
                            Name = "Views",
                            Value = 77.01m
                        },
                        new
                        {
                            VinylDiscId = 37,
                            MusicGenreId = 1,
                            Name = "The Truth About Love",
                            Value = 66.77m
                        },
                        new
                        {
                            VinylDiscId = 38,
                            MusicGenreId = 1,
                            Name = "Bangerz (Deluxe Version)",
                            Value = 58.56m
                        },
                        new
                        {
                            VinylDiscId = 39,
                            MusicGenreId = 1,
                            Name = "DAMN.",
                            Value = 14.09m
                        },
                        new
                        {
                            VinylDiscId = 40,
                            MusicGenreId = 1,
                            Name = "I Decided.",
                            Value = 96.91m
                        },
                        new
                        {
                            VinylDiscId = 41,
                            MusicGenreId = 1,
                            Name = "Funk Wav Bounces Vol.1",
                            Value = 53.80m
                        },
                        new
                        {
                            VinylDiscId = 42,
                            MusicGenreId = 1,
                            Name = "Something New",
                            Value = 19.68m
                        },
                        new
                        {
                            VinylDiscId = 43,
                            MusicGenreId = 1,
                            Name = "÷ (Deluxe)",
                            Value = 60.09m
                        },
                        new
                        {
                            VinylDiscId = 44,
                            MusicGenreId = 1,
                            Name = "PRISM (Deluxe)",
                            Value = 11.30m
                        },
                        new
                        {
                            VinylDiscId = 45,
                            MusicGenreId = 1,
                            Name = "Bangerz (Deluxe Version)",
                            Value = 54.49m
                        },
                        new
                        {
                            VinylDiscId = 46,
                            MusicGenreId = 1,
                            Name = "Bombs Away",
                            Value = 89.10m
                        },
                        new
                        {
                            VinylDiscId = 47,
                            MusicGenreId = 1,
                            Name = "Perfect Strangers",
                            Value = 66.58m
                        },
                        new
                        {
                            VinylDiscId = 48,
                            MusicGenreId = 1,
                            Name = "All This Bad Blood",
                            Value = 23.85m
                        },
                        new
                        {
                            VinylDiscId = 49,
                            MusicGenreId = 1,
                            Name = "Talking Dreams (Deluxe Version)",
                            Value = 65.27m
                        },
                        new
                        {
                            VinylDiscId = 50,
                            MusicGenreId = 1,
                            Name = "Lady Wood",
                            Value = 29.82m
                        },
                        new
                        {
                            VinylDiscId = 51,
                            MusicGenreId = 2,
                            Name = "De Lá Até Aqui",
                            Value = 96.95m
                        },
                        new
                        {
                            VinylDiscId = 52,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 25.42m
                        },
                        new
                        {
                            VinylDiscId = 53,
                            MusicGenreId = 2,
                            Name = "Seu Jorge and Almaz",
                            Value = 13.75m
                        },
                        new
                        {
                            VinylDiscId = 54,
                            MusicGenreId = 2,
                            Name = "I Love MPB - O Nosso Amor A Gente Inventa",
                            Value = 41.16m
                        },
                        new
                        {
                            VinylDiscId = 55,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 53.67m
                        },
                        new
                        {
                            VinylDiscId = 56,
                            MusicGenreId = 2,
                            Name = "A revolta dos ritmos",
                            Value = 73.06m
                        },
                        new
                        {
                            VinylDiscId = 57,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 85.53m
                        },
                        new
                        {
                            VinylDiscId = 58,
                            MusicGenreId = 2,
                            Name = "Meu Coração Não Quer Viver Batendo Devagar",
                            Value = 88.15m
                        },
                        new
                        {
                            VinylDiscId = 59,
                            MusicGenreId = 2,
                            Name = "ôÔÔôôÔôÔ",
                            Value = 54.94m
                        },
                        new
                        {
                            VinylDiscId = 60,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 51.61m
                        },
                        new
                        {
                            VinylDiscId = 61,
                            MusicGenreId = 2,
                            Name = "O Micróbio do Samba",
                            Value = 91.02m
                        },
                        new
                        {
                            VinylDiscId = 62,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 80.60m
                        },
                        new
                        {
                            VinylDiscId = 63,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 95.93m
                        },
                        new
                        {
                            VinylDiscId = 64,
                            MusicGenreId = 2,
                            Name = "I Love MPB - O Nosso Amor A Gente Inventa",
                            Value = 22.06m
                        },
                        new
                        {
                            VinylDiscId = 65,
                            MusicGenreId = 2,
                            Name = "É Proibido Fumar (Remasterizado)",
                            Value = 48.63m
                        },
                        new
                        {
                            VinylDiscId = 66,
                            MusicGenreId = 2,
                            Name = "ôÔÔôôÔôÔ",
                            Value = 58.94m
                        },
                        new
                        {
                            VinylDiscId = 67,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 87.76m
                        },
                        new
                        {
                            VinylDiscId = 68,
                            MusicGenreId = 2,
                            Name = "Feito Pra Acabar",
                            Value = 80.52m
                        },
                        new
                        {
                            VinylDiscId = 69,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 81.15m
                        },
                        new
                        {
                            VinylDiscId = 70,
                            MusicGenreId = 2,
                            Name = "Vanessa da Mata canta Tom Jobim (Deluxe Edition)",
                            Value = 46.02m
                        },
                        new
                        {
                            VinylDiscId = 71,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 63.65m
                        },
                        new
                        {
                            VinylDiscId = 72,
                            MusicGenreId = 2,
                            Name = "Ana E Jorge",
                            Value = 77.05m
                        },
                        new
                        {
                            VinylDiscId = 73,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 76.57m
                        },
                        new
                        {
                            VinylDiscId = 74,
                            MusicGenreId = 2,
                            Name = "De Lá Até Aqui",
                            Value = 57.03m
                        },
                        new
                        {
                            VinylDiscId = 75,
                            MusicGenreId = 2,
                            Name = "ôÔÔôôÔôÔ",
                            Value = 18.95m
                        },
                        new
                        {
                            VinylDiscId = 76,
                            MusicGenreId = 2,
                            Name = "Fôlego",
                            Value = 25.21m
                        },
                        new
                        {
                            VinylDiscId = 77,
                            MusicGenreId = 2,
                            Name = "I Love MPB - O Nosso Amor A Gente Inventa",
                            Value = 28.28m
                        },
                        new
                        {
                            VinylDiscId = 78,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 44.62m
                        },
                        new
                        {
                            VinylDiscId = 79,
                            MusicGenreId = 2,
                            Name = "Volta",
                            Value = 91.65m
                        },
                        new
                        {
                            VinylDiscId = 80,
                            MusicGenreId = 2,
                            Name = "Brasis",
                            Value = 86.66m
                        },
                        new
                        {
                            VinylDiscId = 81,
                            MusicGenreId = 2,
                            Name = "De Lá Até Aqui",
                            Value = 78.85m
                        },
                        new
                        {
                            VinylDiscId = 82,
                            MusicGenreId = 2,
                            Name = "Toni Ferreira",
                            Value = 83.54m
                        },
                        new
                        {
                            VinylDiscId = 83,
                            MusicGenreId = 2,
                            Name = "Mais uma Página",
                            Value = 92.64m
                        },
                        new
                        {
                            VinylDiscId = 84,
                            MusicGenreId = 2,
                            Name = "Chão",
                            Value = 55.43m
                        },
                        new
                        {
                            VinylDiscId = 85,
                            MusicGenreId = 2,
                            Name = "Recanto",
                            Value = 48.48m
                        },
                        new
                        {
                            VinylDiscId = 86,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 72.63m
                        },
                        new
                        {
                            VinylDiscId = 87,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 51.23m
                        },
                        new
                        {
                            VinylDiscId = 88,
                            MusicGenreId = 2,
                            Name = "Baião de Dois",
                            Value = 89.87m
                        },
                        new
                        {
                            VinylDiscId = 89,
                            MusicGenreId = 2,
                            Name = "Sinais dos Tempos",
                            Value = 52.50m
                        },
                        new
                        {
                            VinylDiscId = 90,
                            MusicGenreId = 2,
                            Name = "Dani Black",
                            Value = 26.93m
                        },
                        new
                        {
                            VinylDiscId = 91,
                            MusicGenreId = 2,
                            Name = "I Love MPB - O Nosso Amor A Gente Inventa",
                            Value = 91.38m
                        },
                        new
                        {
                            VinylDiscId = 92,
                            MusicGenreId = 2,
                            Name = "Musica do Brasil Antonio Carlos Jobim \"Romántico\"",
                            Value = 78.52m
                        },
                        new
                        {
                            VinylDiscId = 93,
                            MusicGenreId = 2,
                            Name = "O Disco do Ano",
                            Value = 14.52m
                        },
                        new
                        {
                            VinylDiscId = 94,
                            MusicGenreId = 2,
                            Name = "Nós",
                            Value = 62.38m
                        },
                        new
                        {
                            VinylDiscId = 95,
                            MusicGenreId = 2,
                            Name = "Brasis",
                            Value = 16.79m
                        },
                        new
                        {
                            VinylDiscId = 96,
                            MusicGenreId = 2,
                            Name = "Volta",
                            Value = 73.10m
                        },
                        new
                        {
                            VinylDiscId = 97,
                            MusicGenreId = 2,
                            Name = "Musica do Brasil Antonio Carlos Jobim \"Romántico\"",
                            Value = 23.65m
                        },
                        new
                        {
                            VinylDiscId = 98,
                            MusicGenreId = 2,
                            Name = "Ana E Jorge",
                            Value = 48.93m
                        },
                        new
                        {
                            VinylDiscId = 99,
                            MusicGenreId = 2,
                            Name = "Recanto",
                            Value = 62.56m
                        },
                        new
                        {
                            VinylDiscId = 100,
                            MusicGenreId = 2,
                            Name = "O Descobridor Dos Sete Mares",
                            Value = 95.45m
                        },
                        new
                        {
                            VinylDiscId = 101,
                            MusicGenreId = 3,
                            Name = "Satie: Avant-dernières pensées (Bonus Track Version)",
                            Value = 12.24m
                        },
                        new
                        {
                            VinylDiscId = 102,
                            MusicGenreId = 3,
                            Name = "Riceboy Sleeps",
                            Value = 85.96m
                        },
                        new
                        {
                            VinylDiscId = 103,
                            MusicGenreId = 3,
                            Name = "The Essential Itzhak Perlman",
                            Value = 42.61m
                        },
                        new
                        {
                            VinylDiscId = 104,
                            MusicGenreId = 3,
                            Name = "Extreme Classics",
                            Value = 30.15m
                        },
                        new
                        {
                            VinylDiscId = 105,
                            MusicGenreId = 3,
                            Name = "Mozart - Piano Concertos",
                            Value = 66.07m
                        },
                        new
                        {
                            VinylDiscId = 106,
                            MusicGenreId = 3,
                            Name = "Green - Mélodies françaises",
                            Value = 30.80m
                        },
                        new
                        {
                            VinylDiscId = 107,
                            MusicGenreId = 3,
                            Name = "Legends Of The Fall Original Motion Picture Soundtrack",
                            Value = 48.75m
                        },
                        new
                        {
                            VinylDiscId = 108,
                            MusicGenreId = 3,
                            Name = "The Leftovers: Season 1 (Music from the HBO Series)",
                            Value = 56.62m
                        },
                        new
                        {
                            VinylDiscId = 109,
                            MusicGenreId = 3,
                            Name = "Tenore",
                            Value = 33.12m
                        },
                        new
                        {
                            VinylDiscId = 110,
                            MusicGenreId = 3,
                            Name = "Gregorian Chant",
                            Value = 39.36m
                        },
                        new
                        {
                            VinylDiscId = 111,
                            MusicGenreId = 3,
                            Name = "Handel: Messiah",
                            Value = 55.68m
                        },
                        new
                        {
                            VinylDiscId = 112,
                            MusicGenreId = 3,
                            Name = "Alexandre Tharaud. \"Voyage en France\"",
                            Value = 51.81m
                        },
                        new
                        {
                            VinylDiscId = 113,
                            MusicGenreId = 3,
                            Name = "Monteverdi: Vespers of 1610",
                            Value = 96.40m
                        },
                        new
                        {
                            VinylDiscId = 114,
                            MusicGenreId = 3,
                            Name = "Beethoven: The Symphonies",
                            Value = 68.18m
                        },
                        new
                        {
                            VinylDiscId = 115,
                            MusicGenreId = 3,
                            Name = "Mussorgsky: Pictures at an Exhibition, Songs and Dances of Death, Night on Bare Mountain",
                            Value = 72.66m
                        },
                        new
                        {
                            VinylDiscId = 116,
                            MusicGenreId = 3,
                            Name = "Classical Chillout",
                            Value = 18.38m
                        },
                        new
                        {
                            VinylDiscId = 117,
                            MusicGenreId = 3,
                            Name = "French Impressions",
                            Value = 87.86m
                        },
                        new
                        {
                            VinylDiscId = 118,
                            MusicGenreId = 3,
                            Name = "Vivaldi: The Four Seasons/Wind Concertos",
                            Value = 51.40m
                        },
                        new
                        {
                            VinylDiscId = 119,
                            MusicGenreId = 3,
                            Name = "Faure: Requiem, Op. 48 / Pavane, Op. 50",
                            Value = 73.48m
                        },
                        new
                        {
                            VinylDiscId = 120,
                            MusicGenreId = 3,
                            Name = "Beethoven: Piano Sonatas, Vol.3",
                            Value = 75.90m
                        },
                        new
                        {
                            VinylDiscId = 121,
                            MusicGenreId = 3,
                            Name = "Linkages - Piano music by Brahms, Wagner, Schönberg a.o.",
                            Value = 18.61m
                        },
                        new
                        {
                            VinylDiscId = 122,
                            MusicGenreId = 3,
                            Name = "Fragment",
                            Value = 97.79m
                        },
                        new
                        {
                            VinylDiscId = 123,
                            MusicGenreId = 3,
                            Name = "Copland Conducts Copland - Expanded Edition (Fanfare for the Common Man, Appalachian Spring, Old American Songs (Complete), Rodeo: Four Dance Episodes)",
                            Value = 38.92m
                        },
                        new
                        {
                            VinylDiscId = 124,
                            MusicGenreId = 3,
                            Name = "Lefanu: Catena / String Quartet No. 2 / Clarinet Concertino",
                            Value = 65.12m
                        },
                        new
                        {
                            VinylDiscId = 125,
                            MusicGenreId = 3,
                            Name = "Rimsky-Korsakov: Scheherazade, Op. 35; Capriccio espagnol, Op. 34",
                            Value = 54.54m
                        },
                        new
                        {
                            VinylDiscId = 126,
                            MusicGenreId = 3,
                            Name = "Wartime Consolations",
                            Value = 85.03m
                        },
                        new
                        {
                            VinylDiscId = 127,
                            MusicGenreId = 3,
                            Name = "Private Peaceful (Original Motion Picture Soundtrack)",
                            Value = 73.43m
                        },
                        new
                        {
                            VinylDiscId = 128,
                            MusicGenreId = 3,
                            Name = "The 50 Greatest Pieces of Classical Music",
                            Value = 25.08m
                        },
                        new
                        {
                            VinylDiscId = 129,
                            MusicGenreId = 3,
                            Name = "John Williams Plays Bach",
                            Value = 51.14m
                        },
                        new
                        {
                            VinylDiscId = 130,
                            MusicGenreId = 3,
                            Name = "Verdi: Requiem",
                            Value = 45.75m
                        },
                        new
                        {
                            VinylDiscId = 131,
                            MusicGenreId = 3,
                            Name = "Stravinsky: The Firebird / The Rite of Spring",
                            Value = 12.46m
                        },
                        new
                        {
                            VinylDiscId = 132,
                            MusicGenreId = 3,
                            Name = "The Grand Budapest Hotel (Original Soundtrack)",
                            Value = 79.25m
                        },
                        new
                        {
                            VinylDiscId = 133,
                            MusicGenreId = 3,
                            Name = "The Mission: Music From The Motion Picture",
                            Value = 81.96m
                        },
                        new
                        {
                            VinylDiscId = 134,
                            MusicGenreId = 3,
                            Name = "Maurizio Pollini - Schumann Complete Recordings",
                            Value = 96.10m
                        },
                        new
                        {
                            VinylDiscId = 135,
                            MusicGenreId = 3,
                            Name = "The Wind in High Places",
                            Value = 85.32m
                        },
                        new
                        {
                            VinylDiscId = 136,
                            MusicGenreId = 3,
                            Name = "Adams: Absolute Jest & Grand Pianola Music",
                            Value = 92.78m
                        },
                        new
                        {
                            VinylDiscId = 137,
                            MusicGenreId = 3,
                            Name = "Yellow Lounge Vol.3",
                            Value = 51.83m
                        },
                        new
                        {
                            VinylDiscId = 138,
                            MusicGenreId = 3,
                            Name = "Handel: Water Music",
                            Value = 73.39m
                        },
                        new
                        {
                            VinylDiscId = 139,
                            MusicGenreId = 3,
                            Name = "Tchaikovsky: Overture \"1812\"; Marche slave / Borodin: In the Steppes; Polovtsian Dances / Rimsky-Korsakov: Russian Easter; Capriccio",
                            Value = 89.26m
                        },
                        new
                        {
                            VinylDiscId = 140,
                            MusicGenreId = 3,
                            Name = "The Complete Landings",
                            Value = 28.58m
                        },
                        new
                        {
                            VinylDiscId = 141,
                            MusicGenreId = 3,
                            Name = "Inception (Music From The Motion Picture)",
                            Value = 34.78m
                        },
                        new
                        {
                            VinylDiscId = 142,
                            MusicGenreId = 3,
                            Name = "Bach: Cello Suites Nos. 1, 5 & 6",
                            Value = 94.50m
                        },
                        new
                        {
                            VinylDiscId = 143,
                            MusicGenreId = 3,
                            Name = "The Twilight Saga: Breaking Dawn - Part 2 (Original Motion Picture Soundtrack)",
                            Value = 67.66m
                        },
                        new
                        {
                            VinylDiscId = 144,
                            MusicGenreId = 3,
                            Name = "Brahms & Stravinsky: Violin Concertos",
                            Value = 24.04m
                        },
                        new
                        {
                            VinylDiscId = 145,
                            MusicGenreId = 3,
                            Name = "Adams: Harmonielehre - Short Ride in a Fast Machine",
                            Value = 71.15m
                        },
                        new
                        {
                            VinylDiscId = 146,
                            MusicGenreId = 3,
                            Name = "AVATAR Music From The Motion Picture Music Composed and Conducted by James Horner",
                            Value = 50.47m
                        },
                        new
                        {
                            VinylDiscId = 147,
                            MusicGenreId = 3,
                            Name = "Sinkovsky Plays and Sings Vivaldi",
                            Value = 82.02m
                        },
                        new
                        {
                            VinylDiscId = 148,
                            MusicGenreId = 3,
                            Name = "Hero - Music from the Original Soundtrack",
                            Value = 46.24m
                        },
                        new
                        {
                            VinylDiscId = 149,
                            MusicGenreId = 3,
                            Name = "Time Curve: Music for Piano by Philip Glass and William Duckworth",
                            Value = 89.62m
                        },
                        new
                        {
                            VinylDiscId = 150,
                            MusicGenreId = 3,
                            Name = "Ives: Symphony No. 3 / Washington's Birthday",
                            Value = 98.31m
                        },
                        new
                        {
                            VinylDiscId = 151,
                            MusicGenreId = 4,
                            Name = "American Fool",
                            Value = 85.14m
                        },
                        new
                        {
                            VinylDiscId = 152,
                            MusicGenreId = 4,
                            Name = "Jeremy",
                            Value = 72.15m
                        },
                        new
                        {
                            VinylDiscId = 153,
                            MusicGenreId = 4,
                            Name = "A Beautiful Lie",
                            Value = 75.35m
                        },
                        new
                        {
                            VinylDiscId = 154,
                            MusicGenreId = 4,
                            Name = "Wild Frontier",
                            Value = 86.56m
                        },
                        new
                        {
                            VinylDiscId = 155,
                            MusicGenreId = 4,
                            Name = "No More Tears (Expanded Edition)",
                            Value = 87.74m
                        },
                        new
                        {
                            VinylDiscId = 156,
                            MusicGenreId = 4,
                            Name = "YOUNG&DANGEROUS",
                            Value = 14.35m
                        },
                        new
                        {
                            VinylDiscId = 157,
                            MusicGenreId = 4,
                            Name = "Endgame",
                            Value = 57.95m
                        },
                        new
                        {
                            VinylDiscId = 158,
                            MusicGenreId = 4,
                            Name = "For Crying Out Loud (Deluxe)",
                            Value = 77.39m
                        },
                        new
                        {
                            VinylDiscId = 159,
                            MusicGenreId = 4,
                            Name = "Crazy World",
                            Value = 75.51m
                        },
                        new
                        {
                            VinylDiscId = 160,
                            MusicGenreId = 4,
                            Name = "Straight Shooter",
                            Value = 80.94m
                        },
                        new
                        {
                            VinylDiscId = 161,
                            MusicGenreId = 4,
                            Name = "Foreigner (Expanded)",
                            Value = 57.26m
                        },
                        new
                        {
                            VinylDiscId = 162,
                            MusicGenreId = 4,
                            Name = "Going Grey",
                            Value = 34.57m
                        },
                        new
                        {
                            VinylDiscId = 163,
                            MusicGenreId = 4,
                            Name = "Third Eye Blind",
                            Value = 16.38m
                        },
                        new
                        {
                            VinylDiscId = 164,
                            MusicGenreId = 4,
                            Name = "11 Short Stories of Pain & Glory",
                            Value = 87.27m
                        },
                        new
                        {
                            VinylDiscId = 165,
                            MusicGenreId = 4,
                            Name = "The Black Parade",
                            Value = 37.80m
                        },
                        new
                        {
                            VinylDiscId = 166,
                            MusicGenreId = 4,
                            Name = "Wonder What's Next (Expanded Edition)",
                            Value = 76.33m
                        },
                        new
                        {
                            VinylDiscId = 167,
                            MusicGenreId = 4,
                            Name = "Tranquility Base Hotel & Casino",
                            Value = 69.75m
                        },
                        new
                        {
                            VinylDiscId = 168,
                            MusicGenreId = 4,
                            Name = "The Peace And The Panic",
                            Value = 11.20m
                        },
                        new
                        {
                            VinylDiscId = 169,
                            MusicGenreId = 4,
                            Name = "Meteora (Bonus Edition)",
                            Value = 82.76m
                        },
                        new
                        {
                            VinylDiscId = 170,
                            MusicGenreId = 4,
                            Name = "From Under The Cork Tree",
                            Value = 79.78m
                        },
                        new
                        {
                            VinylDiscId = 171,
                            MusicGenreId = 4,
                            Name = "Amaryllis",
                            Value = 66.44m
                        },
                        new
                        {
                            VinylDiscId = 172,
                            MusicGenreId = 4,
                            Name = "Lighting Matches (Deluxe)",
                            Value = 25.38m
                        },
                        new
                        {
                            VinylDiscId = 173,
                            MusicGenreId = 4,
                            Name = "Ill Communication",
                            Value = 62.04m
                        },
                        new
                        {
                            VinylDiscId = 174,
                            MusicGenreId = 4,
                            Name = "Facelift",
                            Value = 55.80m
                        },
                        new
                        {
                            VinylDiscId = 175,
                            MusicGenreId = 4,
                            Name = "Are You Experienced",
                            Value = 52.02m
                        },
                        new
                        {
                            VinylDiscId = 176,
                            MusicGenreId = 4,
                            Name = "Hot Fuss",
                            Value = 24.01m
                        },
                        new
                        {
                            VinylDiscId = 177,
                            MusicGenreId = 4,
                            Name = "World Away",
                            Value = 41.04m
                        },
                        new
                        {
                            VinylDiscId = 178,
                            MusicGenreId = 4,
                            Name = "Spirit (Deluxe)",
                            Value = 25.78m
                        },
                        new
                        {
                            VinylDiscId = 179,
                            MusicGenreId = 4,
                            Name = "Born To Run",
                            Value = 93.87m
                        },
                        new
                        {
                            VinylDiscId = 180,
                            MusicGenreId = 4,
                            Name = "Cross Road",
                            Value = 14.98m
                        },
                        new
                        {
                            VinylDiscId = 181,
                            MusicGenreId = 4,
                            Name = "It's Not Over....The Hits So Far",
                            Value = 13.91m
                        },
                        new
                        {
                            VinylDiscId = 182,
                            MusicGenreId = 4,
                            Name = "Surrealistic Pillow",
                            Value = 38.09m
                        },
                        new
                        {
                            VinylDiscId = 183,
                            MusicGenreId = 4,
                            Name = "Supernatural (Remastered)",
                            Value = 35.36m
                        },
                        new
                        {
                            VinylDiscId = 184,
                            MusicGenreId = 4,
                            Name = "Meteora",
                            Value = 52.73m
                        },
                        new
                        {
                            VinylDiscId = 185,
                            MusicGenreId = 4,
                            Name = "Honky Chateau",
                            Value = 60.51m
                        },
                        new
                        {
                            VinylDiscId = 186,
                            MusicGenreId = 4,
                            Name = "Keep The Faith",
                            Value = 40.21m
                        },
                        new
                        {
                            VinylDiscId = 187,
                            MusicGenreId = 4,
                            Name = "Crazy World",
                            Value = 14.80m
                        },
                        new
                        {
                            VinylDiscId = 188,
                            MusicGenreId = 4,
                            Name = "Nightmare",
                            Value = 95.30m
                        },
                        new
                        {
                            VinylDiscId = 189,
                            MusicGenreId = 4,
                            Name = "The Better Life",
                            Value = 19.26m
                        },
                        new
                        {
                            VinylDiscId = 190,
                            MusicGenreId = 4,
                            Name = "Simulation Theory (Super Deluxe)",
                            Value = 81.87m
                        },
                        new
                        {
                            VinylDiscId = 191,
                            MusicGenreId = 4,
                            Name = "Veni Vidi Vicious",
                            Value = 45.74m
                        },
                        new
                        {
                            VinylDiscId = 192,
                            MusicGenreId = 4,
                            Name = "Tom Petty & The Heartbreakers",
                            Value = 74.34m
                        },
                        new
                        {
                            VinylDiscId = 193,
                            MusicGenreId = 4,
                            Name = "Hydrograd",
                            Value = 97.77m
                        },
                        new
                        {
                            VinylDiscId = 194,
                            MusicGenreId = 4,
                            Name = "RARE",
                            Value = 19.22m
                        },
                        new
                        {
                            VinylDiscId = 195,
                            MusicGenreId = 4,
                            Name = "Rebel Yell",
                            Value = 71.22m
                        },
                        new
                        {
                            VinylDiscId = 196,
                            MusicGenreId = 4,
                            Name = "Led Zeppelin",
                            Value = 11.12m
                        },
                        new
                        {
                            VinylDiscId = 197,
                            MusicGenreId = 4,
                            Name = "Every Six Seconds",
                            Value = 89.02m
                        },
                        new
                        {
                            VinylDiscId = 198,
                            MusicGenreId = 4,
                            Name = "Rumours",
                            Value = 80.29m
                        },
                        new
                        {
                            VinylDiscId = 199,
                            MusicGenreId = 4,
                            Name = "Can't Deny Me",
                            Value = 86.13m
                        },
                        new
                        {
                            VinylDiscId = 200,
                            MusicGenreId = 4,
                            Name = "Revolution Radio",
                            Value = 94.72m
                        });
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.ItemSale", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.Sale", "Sale")
                        .WithMany("ItemSales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VinylRecordSale.Domain.Entities.VinylDisc", "VinylDisc")
                        .WithMany("ItemSales")
                        .HasForeignKey("VinylDiscId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.Sale", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VinylRecordSale.Domain.Entities.VinylDisc", b =>
                {
                    b.HasOne("VinylRecordSale.Domain.Entities.MusicGenre", "MusicGenre")
                        .WithMany("VinylDiscs")
                        .HasForeignKey("MusicGenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
